### ISSUE TITLE
Subtitle offset

### ISSUE THREAD

**Issue by TaakoMagnusen** [jellyfin/jellyfin-androidtv#1234]
### Describe the feature you'd like

The web client has the option to offset subtitle tracks either forwards or backwards with .1 second degree resolution.

Currently there is no way to offset subtitle tracks on the android TV client. This seems like a big missing feature given subtitles often need manual syncing to get them perfect.

**Comment by doc-code-hub** [comment]
I agree!

It is annoying to be able to have a perfect browser experience and a medriocre from the TV on the same content (in relation to subtitle management).

As audio track offset is allowed, subtitle offset should be allowed too!

I believe it is important to ensure a good experience and therefore _I hope that someone with experience_ on the project will take charge of the problem to **_solve it with a PR_**.

![PlzHelpGIF](https://user-images.githubusercontent.com/61033694/158064327-5c331e29-8544-407c-a694-4f179edf355e.gif)

**Comment by MediaMaquina** [comment]
Hey, Where's the subtitle offset on Chromecast app? I don't see it.

**Comment by NilsMoller** [comment]
I also do not see it. Should we create a new issue as a regression?

**Comment by sebastian-meckovski** [comment]
I'm missing this feature on Android TV as this is where I use jellyfin the most. Can you guys please upvote my post here so maybe it'll get more attention https://features.jellyfin.org/posts/3036/subtile-offset-on-android-tv

**Comment by RetroGameTalk** [comment]
> I'm missing this feature on Android TV as this is where I use jellyfin the most. Can you guys please upvote my post here so maybe it'll get more attention https://features.jellyfin.org/posts/3036/subtile-offset-on-android-tv

Done my part!

**Comment by dmi97** [comment]
Not sure why this is closed, it's still an issue on android tv. I do not have permission to re-open the issue.

**Comment by CrabHead** [comment]
This is still an issue. Please re-open

**Comment by jordibeen** [comment]
Why was this issue closed? Seems like a must-have functionality that's still not available for Android users.

**Comment by mschumacher69** [comment]
I agree.

**Comment by Dr-Otter** [comment]
Why is this still closed if it isn't fixed?

**Comment by null-forbidden** [comment]
Reopen this issue please. This is an essential feature imo.
