### ISSUE TITLE
DEBUG builds don't have a logo icon.

### ISSUE THREAD

**Issue by ManuLinares** [jellyfin/jellyfin-androidtv#1322]
### Describe the bug

1. Install debug build apk
2. No logo.

### Application version

Any debug build

### Device information

Amazon Firestick v1 

### Jellyfin server version

~~10.7.7~~ 10.8.4

**Comment by nielsvanvelzen** [comment]
Amazon changed the way app icons work on their AOS fork. We have a workaround for that only for the release icon, debug versions of the app don't have it. There's no plan to change that as it's good-enough for developers (intended audience of the debug version).

**Comment by nielsvanvelzen** [comment]
Well I just heard from @thornbill he intends to fix this so I'm re-opening the issue!

**Comment by hadicharara** [comment]
This should be fixed and can be closed.

**Comment by ManuLinares** [comment]
> This should be fixed and can be closed.

This isn't fixed yet. I've just tested, and still shows "no image" on the logo.

**Comment by hadicharara** [comment]
sorry my bad. I read now that it's an Amazon specific issue.

**Comment by thornbill** [comment]
I think Amazon pushed out an update to their launcher recently that fixed this issue. If you are still seeing it please provide the device model and Fire OS version.

**Comment by ManuLinares** [comment]
> I think Amazon pushed out an update to their launcher recently that fixed this issue. If you are still seeing it please provide the device model and Fire OS version.

[ro.build.version.name]: [Fire OS 5.2.9.0 (680761220)]
[ro.product.model]: [AFTM]
[ro.product.name]: [montoya]

Installed latest FireOS update today.
Installed latest [Jellyfin success](https://github.com/jellyfin/jellyfin-androidtv/actions/workflows/app-build.yaml?query=branch%3Amaster+is%3Asuccess) build today.

Still "broken image" icon.

**Comment by BotBlake** [comment]
This issue should be fixed 👍
