### ISSUE TITLE
[Issue]: FireTV client - after selecting Vertical (Experimental) for a particular show, that show page always crashes on opening.

### ISSUE THREAD

**Issue by deslea** [jellyfin/jellyfin-androidtv#1833]
### Please describe your bug

I have the most recent version of the FireTV client on a FireTV 4K.

While logged in as a regular (non-admin) user on a particular show page in a mixed media library, I selected the Vertical (Experimental) display option. The client immediately crashed. On re-opening that show page, it immediately crashes (so I can't view that show, or get in far enough to change it back). Behaviour persists after restarting the FireTV. All other shows work fine, and that show works fine on other clients.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Clients: Multiple in environment - Chrome, FireTV, Android. FireTV client version is jellyfin-androidtv 0.13.6
- Browser: Chrome
- FFmpeg Version: Whatever was in ffmpeg-master-latest-win64-gpl on 23/6/22
- Playback Method: Direct over wired gigabit local network
- Hardware Acceleration: AMD AMF
- Plugins: AudioDB, Bookshelf, Cover Art Archive, Fanart, MusicBrainz, OMDB, Open SUbtitles, SkinManager (but no skinning used at present, using default), Studio Images, TMDB, TheTVDB
- Reverse Proxy: None
- Base URL: 192.168.x.xx:8096
- Networking: Wired for this client through shared Nighthawk router
- Storage: Two 5TB USB SSDs
```

### Jellyfin logs

```shell
Nothing relevant found. Activity shows "[username] has disconnected from [FireTV device name]"
```

### Please attach any browser or client logs here

Couldn't work out where to get these, sorry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
I can't reproduce this issue so in order to fix it I really need client logs.

**Comment by deslea** [comment]
Happy to provide them, but how do I get them? FireTV is a proprietary system with its own app store, there's nowhere you can go in and install developer tools like ADB that I can see. I have sent all crash reports to developers, there would have been a bunch of them from an Australian IP address 6-7pm GMT+10 10 July 2022, but I don't have any way to see them myself. I can reproduce the issue here, can I somehow intercept those developer reports at router level or something?

**Comment by deslea** [comment]
Never mind the previous message, found Amazon guidance for getting in. (Dropping here in case anyone else wanting FireTV logs stumbles across this from Google - https://developer.amazon.com/docs/fire-tv/connecting-adb-to-device.html). Will try tonight.

**Comment by deslea** [comment]
[logcat2.txt](https://github.com/jellyfin/jellyfin-androidtv/files/9080990/logcat2.txt)

Timeframes of note:

- Had the behaviour several times 2022-07-10 between 18:30 and 19:00 (there are Jellyfin entries at 18:41 that seem to match this)
- Updated the app when offered 2022-07-11 late morning, reproduced behaviour again after restarting, jellyfin entries at 12:01 seem to match this
- Reproduced the behaviour again just now in order to easily find it at the end of the log. There are Jellyfin entries at 2022-07-11 14:51 that match this.

**Comment by deslea** [comment]
Also, an error, this client device is wirelessly networked, not wired, sorry (I was thinking of my set top box right beside it).

**Comment by nielsvanvelzen** [comment]
I think this is the exception that causes the crash, I'll look into it later.

```
07-11 14:51:24.082 12994 12994 E AndroidRuntime: FATAL EXCEPTION: main
07-11 14:51:24.082 12994 12994 E AndroidRuntime: Process: org.jellyfin.androidtv, PID: 12994
07-11 14:51:24.082 12994 12994 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.browsing.StdGridFragment.getCardHeight(StdGridFragment.java:318)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.browsing.StdGridFragment.onCreate(StdGridFragment.java:111)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onCreate(BrowseGridFragment.java:18)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7186)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2964)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-11 14:51:24.082 12994 12994 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by nielsvanvelzen** [comment]
I believe this issue is already fixed for 0.14.

**Comment by deslea** [comment]
That's great news, I'll hold for 0.14. Thanks so much!

**Comment by deslea** [comment]
This problem didn't solve with the next update but did solve in an update after that. Happy to close. Thanks all!
