### ISSUE TITLE
Can't change audio language

### ISSUE THREAD

**Issue by ggogel** [jellyfin/jellyfin-androidtv#230]
**Describe the bug**
I've read about reports of changing the audio language breaking the aspect ratio and whatever. I'd be happy if I could change the language at all. Most of my media has multiple languages and English is not the default language, but I want to watch them in English. Because the app also doesn't pull the default audio setting from my profile, I need to switch the audio language every time. It kind of works on my Fire TV but on my Android TV it just shows the loading circle and after while the app closes. Meaning I can only watch media in the default language or not at all.

This issue is one of the last reasons for keeping emby running parallel...

**To Reproduce**
Load a video file with two language tracks.
Switch to the second language track while the video plays.
Loading circle appears, after a while the app closes.

**Expected behavior**
The video should play with the changed language.

**System (please complete the following information):**
Client: Philips Android TV 8 
Client Version: 0.10.2g
Server: Jellyfin 10.4.3 Docker on CentOS 8

**Comment by dkanada** [comment]
I think this has been fixed already and might be working in the next release.

**Comment by gerrit507** [comment]
Thank you for the fast response.
In the meantime I also found that this was partially a DNS issue of my Android TV. After changing the server address from the local hostname to the IP adress the app works much more smoothly. Nevertheless after switching the audio track it doesn't go into loading anymore but still plays the media with the default audio track.

**Comment by dogmop** [comment]
This still occurs in 0.11.4 for me. The app doesn't close, but the language does not switch.

**To Reproduce**
Load a video file with two language tracks.
Switch to the second language track while the video plays.
Language does not change

**Expected behavior**
The video should play with the changed language.

**System (please complete the following information):**
Client: Sony Android TV
Client Version: 0.11.4
Server: Jellyfin 10.6.4 Docker

**Comment by vocalico** [comment]
> **System (please complete the following information):**
> Client: Sony Android TV
> Client Version: 0.11.4
> Server: Jellyfin 10.6.4 Docker

Exactly the same here but different system configuration

System:
Client: Xiaomi Mi Stick (Android TV)
Client Version: 0.11.4
Server: Jellyfin 10.6.4 (No Docker) Ubuntu 20.04 & Jellyfin 10.6.4 (No Docker) Ubuntu 18.04

**Comment by sn0wD4N** [comment]
I got around the issue although it requires you to install another video player. My choice qas VLC. Then in the Jellyfin settings - playback - player - external player. And within VLC you can actually choose the language and it works as well. Not the perfect solution but works for the meantime.

**Comment by dgalli1** [comment]
This issue seems to still exist with the latest Jellyfin TV client 0.11.5 and Jellyfin 10.7.5

**Comment by dereulenspiegel** [comment]
Yes, it still exists for me with latest Jellyfin Server and Jellyfin Android TV Client on the Fire TV (different from first gen up to latest 4k Stick).

**Comment by MarcStorm** [comment]
I also experience the issue of being unable to swap language audio track for my video content.

The error is easily reproduced on the latest Jellyfin Server and Jellyfin Android TV Client on a NVIDIA Shield TV.
I've not been able to reproduce the problem when using the Jellyfin Web client in Safari. 

Side comment if it help locating the root cause of the issue, I also experience the same problem of being able to changing the subtitles.

**Comment by Xeddius** [comment]
I'm also unable to change subtitles or video language, the web client and regular android client has a simple solution by allowing you to select these at the start of the video on its page. Why this feature has not been mirrored to the androidtv version is mind boggling but it needs to be addressed for feature-parity and consistency purposes, also because it's incredibly inconvenient to have jellyfin work flawlessly across numerous devices only to have issues on the one device (TV) that is central to theatre style media.

**Comment by fonikz** [comment]
I am having this same issue. Movie has two audio tracks
Japanese - AAC - Stereo - Default
English - AAC - Stereo - Default

Web Client and Android Client both only play the Japanese track. I've tried switching audio on the main page, and in the player. In the player, the audio attempts to change and the video reloads, but the track does not change, it stays Japanese.

**Comment by virdb** [comment]
Similar for me, when I switch to English (not my default language, and this is fine), the movie still have the Italian language.
On the audio choiche menu, English is selected.

Seems there is no way to select the audio track before starting the movie.

Only on Android TV on xiaomi tv stick with app from play store. 
Web from pc is working fine like on another smart tv. (using the integrated browser).

**Comment by Haymaker007** [comment]
Describe the bug

I experience this issue with some of my movies and series and only on Android-TV.

"Most of my media has multiple languages and English is not the default language, but I want to watch them in English. Because the app also doesn't pull the default audio setting from my profile, I need to switch the audio language every time. Meaning I can only watch media in the default language or not at all."

This issue is one of the last reasons for keeping emby running parallel...

To Reproduce
"Load a video file with two language tracks.
Switch to the second language track while the video plays.
Loading circle appears, after a while the app" 
states that the audio has been changed, but it remains the same.

Expected behavior
The video should play with the changed language.

System (please complete the following information):
Client: Philips Android TV 10
Client Version: 0.14.5
Server: Jellyfin 10.8.8 Docker on Debian

**Comment by mathgoy** [comment]
Same problem here.
It's been almost 4 years and still not fixed?
How is that possible?

**Comment by catprisbrey** [comment]
Same here, tried on the Jellyfin android app, as well as on my Roku. I can't change the audio from the English to Spanish. The UI will show it's changed but the audio stays as it was, still in English. Testing my files in VLC, they change audio channel no problem.

**Comment by hSpille** [comment]
Same here. Latest docker Image, running Client on FireTV. Additional: In the Client no option to change the language at all.

**Comment by kowlown** [comment]
Same issue. Jellyfin can't detect multiple audio track, and select the English by default. 

- Track 1 : 
     - Codec : A52 Audio (aka AC3) (a52 )
     - Language : French
     - Type : Audio
     - Channel : 3F2M/LFE
- Track 2 : 
     - Codec : A52 Audio (aka AC3) (a52 )
     - Language : French
     - Description: AD
     - Type : Audio
- Track 3 : 
     - Codec : A/52 B Audio (aka E-AC3) (eac3)
     - Language : English
     - Type : Audio

The server choose the English track and didn't detect the French ones. So I can't change to French.

Jellyfin info : Docker version : lscr.io/linuxserver/jellyfin:10.10.7

**Comment by fonikz** [comment]
My issue was that both Japanese and English tracks were marked as default. Had to fix the bad metadata in the file.

**Comment by draperbr** [comment]
<img width="681" height="513" alt="Image" src="https://github.com/user-attachments/assets/b4cb607e-df92-47aa-b4f8-7aa6cfa6801d" />

Multiple Roku players are having the same issue:

- Default language is German
- Player starts playing it in English
- When I go to the audio menu, it shows German is selected
- I switch English, it "loads", and continues playing in English
- I go to the audio menu and I switch back to German
- It "loads" and then starts playing in German

It's as if the player is auto selecting English (even though I have my user profile set to "Any Language" for preferred audio language), but not actually selecting the track in the GUI.  So when I can't change it to German, because German is already selected (despite it playing in English).  So when I select English, it says "oh, you want English, ok" and plays English.  Only when I then switch it BACK to German does it say "oh, you want German, ok."

**Comment by nielsvanvelzen** [comment]
How did you even manage to install an Android TV app on Roku?

**Comment by casmin7** [comment]
This is still an issues
The android tv app will always choose the default audio track regardless of what language the user has as the default
