### ISSUE TITLE
Frame Interpolation not working

### ISSUE THREAD

**Issue by Florianisme** [jellyfin/jellyfin-androidtv#238]
The playback of all of my movies (4K and 1080p) seems like it is locked to 24fps, even though it is played super smoothtly in third party media players such as VLC or MX Player. 
It is a direct stream with no transcoding enabled on the server.

The TV is a 2018 Sony Bravia 4K and it is running Android 8.0.
4K Media playback is no issue on it whatsoever.

**Comment by Florianisme** [comment]
You should definetly consider switching to using ExoPlayer for movie playback. I'm using it in my local build and it's running as smoothly as all the other media players I had to use.

**Comment by nielsvanvelzen** [comment]
We do currently use ExoPlayer 1.5.6 and VLC as fallback

**Comment by Florianisme** [comment]
Then there must be a big performance difference between ExoPlayer 1.X and 2.X as I tested it with 2.11.1

**Comment by nielsvanvelzen** [comment]
I think that might be true, I'm actually working on upgrading to ExoPlayer 2 and so far it seems to work a lot smoother in my emulator! So this issue might be fixed in the future.

If you'd like to track the progress take a look at #244

**Comment by Florianisme** [comment]
Hit me up if you need some help when refactoring or upgrading the code. I also have a working prototype fork of this project using the ExoPlayer 2.X on my profile

**Comment by huudafakk** [comment]
Is there an beta-APK for testing for this case or case #244? I've the same issue reported at the beginning, but I'm new into this all. Thanks in advance

**Comment by nielsvanvelzen** [comment]
For now you would have to clone (or download) the branch and build the app by yourself (using Android Studio helps with this). Unfortunately there is no apk download at the moment.

**Comment by nielsvanvelzen** [comment]
Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

**Comment by Florianisme** [comment]
Issue might be closed now unless @huudafakk still encounters problems even with the update 0.11.

**Comment by nielsvanvelzen** [comment]
I'll close it for now and we can always re-open.

**Comment by huudafakk** [comment]
with the 0.11.x release I didn't encounter this problem, we could also close Issue `113`
