### ISSUE TITLE
Live Tv Guide: Load channels null - null 

### ISSUE THREAD

**Issue by helptiger** [jellyfin/jellyfin-androidtv#2633]
### Describe the bug

Live TV Guide
There must be more than 75 entries so that a page change can take place. 
scroll down & look at the bottom label
 
![page](https://user-images.githubusercontent.com/10258902/229448162-c1fd5c1a-89b7-4c2b-b645-2433d51ceaec.jpg)

### Application version

0.15.5

### Where did you install the app from?

Google Play

### Device information

Sony Bravia atv3

### Android version

Android 9

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Thanks for the report, should be fixed in the next release.

**Comment by helptiger** [comment]
For me it is not fixed. Only Loading Channel is displayed - no numbers or the button shows no text at all.

**Comment by nielsvanvelzen** [comment]
The numbers will only show when they are available now. So in your specific case the app doesn't get any channel numbers from the server and will fallback to not display those.

**Comment by helptiger** [comment]
![IMG_5704](https://user-images.githubusercontent.com/10258902/230062693-d9017256-52c0-4c99-aacb-0a88572f65c2.jpg)

I do not quite understand, since the number of channels are displayed. The numbers seem to be there (see bottom left).

**Comment by nielsvanvelzen** [comment]
Those are not the actual channel id's but just the count of the shown items.
