### ISSUE TITLE
MKV stutters and hangs multiple times during first few minutes of playback.

### ISSUE THREAD

**Issue by callingshotgun** [jellyfin/jellyfin-androidtv#277]
I have an 88 minute long MKV file. It consistently hangs multiple times over the first few minutes of playback, but only on the Android TV client.  The file contains subtitles, but I'm not showing them when the issue occurs.

- Device I'm testing on is the JBL Link Bar, which has Android 9.0 Pie (SDK Version 28).

- Connected by ethernet to the network, so not a wifi reception issue.

- Only occurs when I have "Downmix to Stereo" enabled.  However when that box isn't checked, can't hear any audio.
So issue seems related to transcoding audio.

- Per request in the other thread, , I verified this was happening on Master and not just on theversion currently in the Google Play Store.

- When I'm connected via ADB, logcat shows the following line every time the video freezes:
2020-01-23 21:15:58.507 15601-16402/org.jellyfin.androidtv.debug I/AudioTrack: calling pause

- Media info (as reported by VLC):
Stream 0
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Language: English
Type: Video
Video resolution: 1920x1080
Buffer dimensions: 1920x1088
Frame rate: 23.976215
Decoded format: 
Orientation: Top left
Chroma location: Left

Stream 1
Codec: DTS Audio (dts )
Language: English
Type: Audio
Channels: Stereo
Sample rate: 48000 Hz
Bits per sample: 32

- Ripped from physical media using MakeMKV.

_Originally posted by @callingshotgun in https://github.com/jellyfin/jellyfin-androidtv/issues/130#issuecomment-576508673_

**Comment by booksarestillbetter** [comment]
i can confirm i have this issue as well. plays fine on my pixel 3, but my android tv has massive stuttering.  this is on a shield 2019 pro. using play store version. i can test the latest master if need but appears @callingshotgun already test.

> General
Complete name                            : True Lies 1994.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 4.34 GiB
Duration                                 : 2 h 20 min
Overall bit rate                         : 4 416 kb/s
Encoded date                             : UTC 2018-03-13 4:19:22
Writing application                      : mkvmerge v6.1.0
Writing library                          : libebml v1.3.0 + libmatroska v1.4.0

> Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : 2 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 2 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 20 min
Bit rate                                 : 3 944 kb/s
Width                                    : 1 280 pixels
Height                                   : 546 pixels
Display aspect ratio                     : 2.35:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.235
Stream size                              : 3.88 GiB (89%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

> Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 20 min
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 387 MiB (9%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

**Comment by PricklyNarwhal** [comment]
Having the same issue here.  Disabling Refresh Rate Switching in the settings seems to help.

**Comment by nielsvanvelzen** [comment]
Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

**Comment by callingshotgun** [comment]
Unfortunately, I'm still seeing it :(  Not an issue when I check off playing in VLC instead.

**Comment by booksarestillbetter** [comment]
if i turn off auto refresh it does help, but its still not perfect.

**Comment by tekmad** [comment]
My Shield TV 2017 has been experiencing frequent stutter on most content, it seems improved on 0.11.1
But it still happens, a pause - resume clears it.

**Comment by brianclinkenbeard** [comment]
This continues to happen with MKV files on my TV, seemingly being an issue with ExoPlayer.

**Comment by brianclinkenbeard** [comment]
This issue still occurs for me.

**Comment by tekmad** [comment]
Tested today, still happening. Pause/play no longer worked to clear the affect.

**Comment by ghzgod** [comment]
Same as tekmad mentions.  Still happening
