### ISSUE TITLE
Grouped video version selection does nothing for playback

### ISSUE THREAD

**Issue by Janhouse** [jellyfin/jellyfin-androidtv#3183]
### Describe the bug

I have grouped 2 video files for the same movie.
One is 4k in English, and the other one is 1080p in multiple languages.

Clicking the `Version` button in the TV app interface shows all available files, and selecting different versions indicates that a different version has been selected (since resolution tag changes, but the audio channel tag does not change).

But no matter which version I choose, clicking `Play` button still plays the default version, not the one I selected.

It does work correctly from web, iOS and Desktop applications, seems like only Android TV application has this problem.

### Application version

0.15.2

### Device information

Bravia 4K VH2

### Android version

Android TV OS 10

### Jellyfin server version

10.8.12

**Comment by MichaelRUSF** [comment]
Same issue as #1521. In testing out the 10.9 server, it seems the issue has been fixed.  I think it was a file stacking / name convention issue. 

If you followed the [documentation](https://jellyfin.org/docs/general/server/media/movies/#multiple-versions-of-a-movie) on naming for 10.8, it's not going to work as expected. Workaround for server 10.8 would be to name files in alphabetical order making sure higher resolution is listed first in alphabetical order.  

Naming convention 10.8 example:
Folder -->The Movie (1999)
File -------->The Movie (1999) - **DVHDR** 2160p
File -------->The Movie (1999) - **SDR** 1080p

**Comment by kjvalencik** [comment]
I'm seeing the same issue, but with slightly different behavior.

1. Always playing 2 of 2
2. Reporting the runtime of the selected file
3. Not fixed by 10.9 server
