### ISSUE TITLE
Player error encountered

### ISSUE THREAD

**Issue by 13Angels** [jellyfin/jellyfin-androidtv#3850]
### Describe the bug

I'm encountering a player error on my Amazon Fire TV Toshiba HD. I play the movie, and after a few seconds it says "Player Error encountered, re-trying...Too many errors, giving up." This error only happens on this device, all other TVs and computers work perfectly fine. Also, this error happens for a wide variety of movies, with different codecs too. I can't seem to find a correlation between any of them. Looking at the log, it seems the transcoding just stops completely, for no apparent reason. 

### Logs

```
{"Protocol":0,"Id":"b64642dff3b97f9375d3ec873c909e21","Path":"I:\\p\\p\\A Quiet Place Day One (2024)\\A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX\\A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv","Size":11468517123,"Name":"A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX","IsRemote":false,"ETag":"b669999bb568fac566db5d076507085d","RunTimeTicks":60927950000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"","VideoRange":1,"VideoRangeType":1,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"4K HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":15058464,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1600,"Width":3840,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main","Type":1,"AspectRatio":"2.40:1","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":150,"IsAnamorphic":false},{"Codec":"eac3","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Default","LocalizedForced":null,"LocalizedExternal":"External","LocalizedHearingImpaired":null,"DisplayTitle":"English - Dolby Digital\u002B - 5.1 - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"5.1","BitRate":768000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"English - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"SDH","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"SDH - English - Hearing Impaired - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":true,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Canadian","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"Canadian - Fre - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":15826464,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts  -i file:"I:\p\p\A Quiet Place Day One (2024)\A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX\A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c.m3u8"


ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13-win32 (GCC)
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from 'file:I:\p\p\A Quiet Place Day One (2024)\A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX\A Quiet Place Day One 2024 2160p AMZN WEB-DL DDP5 1 H 265-FLUX.mkv':
  Metadata:
    title           : 
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
  Duration: 01:41:32.80, start: 0.000000, bitrate: 15058 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 495.995000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 495.995000, end 816.816000
      Metadata:
        title           : Chapter 02
    Chapter #0:2: start 816.816000, end 1240.115000
      Metadata:
        title           : Chapter 03
    Chapter #0:3: start 1240.115000, end 1743.076000
      Metadata:
        title           : Chapter 04
    Chapter #0:4: start 1743.076000, end 2278.945000
      Metadata:
        title           : Chapter 05
    Chapter #0:5: start 2278.945000, end 2954.454000
      Metadata:
        title           : Chapter 06
    Chapter #0:6: start 2954.454000, end 3574.240000
      Metadata:
        title           : Chapter 07
    Chapter #0:7: start 3574.240000, end 4268.810000
      Metadata:
        title           : Chapter 08
    Chapter #0:8: start 4268.810000, end 4752.210000
      Metadata:
        title           : Chapter 09
    Chapter #0:9: start 4752.210000, end 5321.529000
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 5321.529000, end 6092.795000
      Metadata:
        title           : Chapter 11
  Stream #0:0(eng): Video: hevc (Main), yuv420p(tv, bt709), 3840x1600 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default) (original)
    Metadata:
      title           : 
  Stream #0:1(eng): Audio: eac3 (Dolby Digital Plus + Dolby Atmos), 48000 Hz, 5.1(side), fltp, 768 kb/s (default) (original)
    Metadata:
      title           : 
  Stream #0:2(eng): Subtitle: subrip (original)
    Metadata:
      title           : 
  Stream #0:3(eng): Subtitle: subrip (original) (hearing impaired)
    Metadata:
      title           : SDH
  Stream #0:4(fre): Subtitle: subrip (dub)
    Metadata:
      title           : Canadian
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, hls, to 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 3840x1600 [SAR 1:1 DAR 12:5], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn (default) (original)
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s (default) (original)
    Metadata:
      encoder         : Lavc60.3.100 libfdk_aac
frame=    1 fps=0.0 q=-1.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 00000268961d0c80] Opening 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c0.ts' for writing
[hls @ 00000268961d0c80] Opening 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c1.ts' for writing
[hls @ 00000268961d0c80] Opening 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c2.ts' for writing
[hls @ 00000268961d0c80] Opening 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c3.ts' for writing
[hls @ 00000268961d0c80] Opening 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c4.ts' for writing
frame=  774 fps=0.0 q=-1.0 size=N/A time=00:00:32.49 bitrate=N/A speed=64.9x    


[q] command received. Exiting.

[hls @ 00000268961d0c80] Opening 'C:\Users\angel\Documents\Jellyfin\transcodes\6e285926ac6eb88be44df7762707e85c5.ts' for writing
frame=  779 fps=0.0 q=-1.0 Lsize=N/A time=00:00:32.55 bitrate=N/A speed=64.4x    
video:57592kB audio:1018kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

### Application version

0.17.0

### Where did you install the app from?

Amazon Appstore

### Device information

Toshiba HD - Fire TV (2018-2020)

### Android version

Fire OS 6

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
In the app preferences, go to playback then set "Audio output" to "Direct". It defaults to "Downmix to stereo", which will force transcoding for a lot of audio codecs.

**Comment by locqust** [comment]
I also have this issue. Only on a Firestick at with app at V.0.17.1or V.0.17.0
Works fine on a JVC Fire TV on V.0.17.0, Android phones and tablets running V2.6.x. 
On the Firestick it tries to play any x265/HEVC file, after a couple of seconds of blank screen it pops up with the same error as O.P. 

I've tried switching the Audio Output to Direct, I've changed bitrates, even tried switching to external player (VLC). It starts to try to play with VLC, sounds comes out but I get a corrupted frame of the video every 5 seconds or so.

Downgraded app back to 0.16.11 and reselected 'use libVLC' as the player and it works perfectly.
All other devices set to use internal player and can play the file fine.

**Comment by 13Angels** [comment]
> In the app preferences, go to playback then set "Audio output" to "Direct". It defaults to "Downmix to stereo", which will force transcoding for a lot of audio codecs.

I have indeed done that. Still the same issue.

**Comment by fredmorais** [comment]
I am having the same issue and I actually solved it the other way around. Changed from "Direct" to "Downmix" and now it works.

**Comment by bobby3605** [comment]
> I am having the same issue and I actually solved it the other way around. Changed from "Direct" to "Downmix" and now it works.

Had the same issue. This resolved it for me as well. I'm not seeing a crash log on my server, just a generic message about playback stopping.

**Comment by nielsvanvelzen** [comment]
I believe this issue is fixed with the next release via (#3875). Older FireOS devices don't support HEVC but the app wrongfully thought it did when it needed to transcode.

**Comment by Jonas-Sander** [comment]
I had some success getting a movie to play when selecting downmixing to stereo but still have this issue on other movies/series with no apparent way to fix :(

**Comment by 99linesofcode** [comment]
Seems I run into this everytime a Bluetooth speaker, headset or earbud is connected and always when audio is DD 5.1 or DD+. Changing from 'direct' to 'downmix to stereo' works for me as well.

Potentially this is an issue with our streaming device or the audio devices not supporting surround sound.
