### ISSUE TITLE
Crash after waking up TV from sleep

### ISSUE THREAD

**Issue by bebsworthy** [jellyfin/jellyfin-androidtv#4073]
### Describe the bug

First launch after resuming from sleep always crash. Second launch works.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.6
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to org.jellyfin.androidtv.ui.browsing.HistoryEntry[]
	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.onRestoreInstanceState(DestinationFragmentView.kt:184)
	at android.view.View.dispatchRestoreInstanceState(View.java:21017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4000)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
	at android.view.View.restoreHierarchyState(View.java:20995)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2200)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1724)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1677)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1376)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3676)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

[....]
10-13 14:35:53.981 V/io.ktor.client.plugins.defaultTransformers(26332): Transformed with default transformers response body for http://192.168.1.2:8096/Items/Latest?fields=Overview&includeItemTypes=Episode&isPlayed=false&limit=50&groupItems=true to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
--------- beginning of crash
10-13 14:35:53.985 E/AndroidRuntime(26332): FATAL EXCEPTION: main
10-13 14:35:53.985 E/AndroidRuntime(26332): Process: org.jellyfin.androidtv, PID: 26332
10-13 14:35:53.985 E/AndroidRuntime(26332): java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to org.jellyfin.androidtv.ui.browsing.HistoryEntry[]
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.onRestoreInstanceState(DestinationFragmentView.kt:184)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.view.View.dispatchRestoreInstanceState(View.java:21017)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4000)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.view.View.restoreHierarchyState(View.java:20995)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2200)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.Activity.onRestoreInstanceState(Activity.java:1724)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.Activity.performRestoreInstanceState(Activity.java:1677)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1376)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3676)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.os.Looper.loopOnce(Looper.java:201)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.os.Looper.loop(Looper.java:288)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at java.lang.reflect.Method.invoke(Native Method)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-13 14:35:53.985 E/AndroidRuntime(26332): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
10-13 14:35:53.988 E/ACRA    (26332): ACRA caught a ClassCastException for org.jellyfin.androidtv
```

### App information

***App version***: `0.17.6` (`170699`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"boreal","BOOTLOADER":"01.01.240305.091750","BRAND":"google","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"boreal","DISPLAY":"STTE.240615.007","FINGERPRINT":"google\/boreal\/boreal:12\/STTE.240615.007\/12033466:user\/release-keys","HARDWARE":"amlogic","HOST":"r-d3d21742fc70d910-13wg","ID":"STTE.240615.007","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Chromecast HD","ODM_SKU":"unknown","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"boreal","RADIO":"unknown","SKU":"FR","SOC_MANUFACTURER":"Amlogic","SOC_MODEL":"AMLS805X2","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1719773501000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"12033466","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2024-07-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170699,"VERSION_NAME":"0.17.6"}
```  

### Device information

***Android version***: `12`  
***Device brand***: `google`  
***Device product***: `boreal`  
***Device model***: `Chromecast HD`  

### Crash information

***Start time***: `2024-10-13T13:04:32.960+02:00`  
***Crash time***: `2024-10-13T14:35:54.346+02:00`  

### Application version

0.17.6

### Where did you install the app from?

Google Play

### Device information

Chromecast HD

### Android version

12

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
I wasn't able to reproduce the issue but I made some changes that might fix them. Let me know if the issue still occurs in the 0.17.7 release once updated.

**Comment by nielsvanvelzen** [comment]
The mentioned fix was somehow not included in 0.17.7 so please test again with 0.17.8.

**Comment by hammyexe** [comment]
> The mentioned fix was somehow not included in 0.17.7 so please test again with 0.17.8.

Yes thank you, the issue has been resolved.

**Comment by bebsworthy** [comment]
I haven't had the issue today, the issue seems fixed. Thanks

**Comment by bebsworthy** [comment]
I wrote too fast. The apparent behavior is still the same (Crash on launch) but the error is different.

Same that reported in this issue https://github.com/jellyfin/jellyfin-androidtv/issues/4099

**Comment by hammyexe** [comment]
I also spoke too soon, the issue still persists on 0.17.8.

**Comment by nielsvanvelzen** [comment]
The issue from this issue was fixed. The issue with "FragmentManager is already executing transactions" is different but somewhat similar. We'll track it in #4099.
