### ISSUE TITLE
Jellyfin crashes after a few minutes.

### ISSUE THREAD

**Issue by heggrik** [jellyfin/jellyfin-androidtv#4218]
I answered in a closed issue, opening a new one and referencing the old.

> I have this same issue on 17.9 it started a few days ago, 
> 
> Works on web, or on tv when using external player but not within jellyfin using exoplayer.
> 
> ---
> client: Jellyfin for Android TV
> client_version: 0.17.9
> client_repository: https://github.com/jellyfin/jellyfin-androidtv
> type: crash_report
> format: markdown
> ---
> ### Logs
> 
> ***Stack Trace***: 
> ```log
> java.lang.IllegalStateException: FragmentManager is already executing transactions
> 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1937)
> 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
> 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
> 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.activateHistoryEntry(DestinationFragmentView.kt:159)
> 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.goBack(DestinationFragmentView.kt:113)
> 	at org.jellyfin.androidtv.ui.browsing.MainActivity.handleNavigationAction(MainActivity.kt:117)
> 	at org.jellyfin.androidtv.ui.browsing.MainActivity.access$handleNavigationAction(MainActivity.kt:33)
> 	at org.jellyfin.androidtv.ui.browsing.MainActivity$onCreate$2.invokeSuspend(MainActivity.kt:66)
> 	at org.jellyfin.androidtv.ui.browsing.MainActivity$onCreate$2.invoke(Unknown Source:8)
> 	at org.jellyfin.androidtv.ui.browsing.MainActivity$onCreate$2.invoke(Unknown Source:4)
> 	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:219)
> 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
> 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
> 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
> 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:241)
> 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
> 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466)
> 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500)
> 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489)
> 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
> 	at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:409)
> 	at org.jellyfin.androidtv.ui.navigation.NavigationRepositoryImpl.goBack(NavigationRepository.kt:93)
> 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.closePlayer(CustomPlaybackOverlayFragment.java:1314)
> 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onStop(CustomPlaybackOverlayFragment.java:730)
> 	at androidx.fragment.app.Fragment.performStop(Fragment.java:3346)
> 	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:700)
> 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:324)
> 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
> 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
> 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
> 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
> 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.activateHistoryEntry(DestinationFragmentView.kt:159)
> 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.onRestoreInstanceState(DestinationFragmentView.kt:187)
> 	at android.view.View.dispatchRestoreInstanceState(View.java:20743)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3986)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.View.restoreHierarchyState(View.java:20721)
> 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2181)
> 	at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
> 	at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
> 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
> 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3491)
> 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
> 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
> 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:223)
> 	at android.app.ActivityThread.main(ActivityThread.java:7656)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bb5ef2f, Dispatchers.Main.immediate]
> 
> ```  
> ***Logcat***: 
> ```log
> 11-15 22:50:35.673 D/MediaCodec( 5678): flushMediametrics
> 11-15 22:50:35.674 D/MediaCodec( 5678): flushMediametrics
> 11-15 22:50:35.685 D/NavigationRepositoryImpl( 5678): Navigating back
> 11-15 22:50:35.711 D/MainActivity$onStop( 5678): MainActivity stopped
> 11-15 22:50:35.716 I/SessionRepositoryImpl$restoreSession( 5678): Restoring session
> 11-15 22:50:35.732 D/ACRA    ( 5678): onActivitySaveInstanceState class org.jellyfin.androidtv.ui.browsing.MainActivity
> 11-15 22:50:35.742 D/ACRA    ( 5678): onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.MainActivity
> 11-15 22:50:35.764 D/Compose Focus( 5678): Owner FocusChanged(true)
> 11-15 22:50:35.788 W/libEGL  ( 5678): EGLNativeWindowType 0xac5c7008 disconnect failed
> 11-15 22:50:35.843 D/ACRA    ( 5678): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
> 11-15 22:50:35.885 D/DefaultPlayerQueueState( 5678): Queue changed, setting index to 0
> 11-15 22:50:35.888 I/PlaybackController( 5678): ** Available display refresh rates:
> 11-15 22:50:35.888 D/PlaybackController( 5678): display mode 1 - 1920x1080@60.000004
> 11-15 22:50:35.896 I/org.jellyfin.sdk.api.ktor.KtorClient( 5678): GET https://jelly.nilsenius.nu/LiveTv/Programs/Recommended?limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
> 11-15 22:50:35.898 I/HomeRowsFragment( 5678): Updating audio queue in HomeFragment (onQueueStatusChanged)
> 11-15 22:50:35.900 V/io.ktor.client.plugins.HttpPlainText( 5678): Adding Accept-Charset=UTF-8 to https://jelly.nilsenius.nu/LiveTv/Programs/Recommended?limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
> 11-15 22:50:35.918 D/ACRA    ( 5678): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
> 11-15 22:50:35.983 V/io.ktor.client.plugins.HttpCallValidator( 5678): Validating response for request https://jelly.nilsenius.nu/LiveTv/Programs/Recommended?limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
> 11-15 22:50:35.984 V/io.ktor.client.plugins.DefaultResponseValidation( 5678): Skipping default response validation for https://jelly.nilsenius.nu/LiveTv/Programs/Recommended?limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false
> 11-15 22:50:35.987 V/io.ktor.client.plugins.defaultTransformers( 5678): Transformed with default transformers response body for https://jelly.nilsenius.nu/LiveTv/Programs/Recommended?limit=1&isAiring=true&imageTypeLimit=1&enableTotalRecordCount=false to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
> 11-15 22:50:36.015 I/ExoPlayerImpl( 5678): Init 9f8d07c [AndroidXMedia3/1.4.1] [PH0M_EA_T32, Philips UHD Android TV, TPV, 30]
> 11-15 22:50:36.016 I/DefaultRenderersFactory( 5678): Loaded FfmpegVideoRenderer.
> 11-15 22:50:36.022 I/DefaultRenderersFactory( 5678): Loaded FfmpegAudioRenderer.
> 11-15 22:50:36.044 I/PlaybackController( 5678): Play called from state: IDLE with pos: 0 and sub index: null
> 11-15 22:50:36.045 D/PlaybackController( 5678): Max bitrate is: 100000000
> 11-15 22:50:36.050 D/jellyfin-apiclient( 5678): Adding request to queue: https://jelly.nilsenius.nu/Items/849facee-36d8-1195-6e43-672bac76a69a/PlaybackInfo?format=json
> 11-15 22:50:36.060 D/CustomPlaybackOverlayFragment( 5678): Stopping!
> 11-15 22:50:36.061 D/CustomPlaybackOverlayFragment( 5678): this fragment belongs to the current session, ending it
> 11-15 22:50:36.061 D/PlaybackController( 5678): stop called at 0
> 11-15 22:50:36.063 I/ExoPlayerImpl( 5678): Release 9f8d07c [AndroidXMedia3/1.4.1] [PH0M_EA_T32, Philips UHD Android TV, TPV, 30] [media3.common, media3.exoplayer, media3.decoder, media3.session, media3.ui, media3.datasource, media3.extractor, media3.decoder.ffmpeg]
> 11-15 22:50:36.065 D/NavigationRepositoryImpl( 5678): Navigating back
> 11-15 22:50:36.070 E/ACRA    ( 5678): ACRA caught a IllegalStateException for org.jellyfin.androidtv
> 11-15 22:50:36.070 E/ACRA    ( 5678): java.lang.IllegalStateException: FragmentManager is already executing transactions
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1937)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.activateHistoryEntry(DestinationFragmentView.kt:159)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.goBack(DestinationFragmentView.kt:113)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.handleNavigationAction(MainActivity.kt:117)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.MainActivity.access$handleNavigationAction(MainActivity.kt:33)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.MainActivity$onCreate$2.invokeSuspend(MainActivity.kt:66)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.MainActivity$onCreate$2.invoke(Unknown Source:8)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.MainActivity$onCreate$2.invoke(Unknown Source:4)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:219)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:241)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:409)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.navigation.NavigationRepositoryImpl.goBack(NavigationRepository.kt:93)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.closePlayer(CustomPlaybackOverlayFragment.java:1314)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onStop(CustomPlaybackOverlayFragment.java:730)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.Fragment.performStop(Fragment.java:3346)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:700)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:324)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.activateHistoryEntry(DestinationFragmentView.kt:159)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at org.jellyfin.androidtv.ui.browsing.DestinationFragmentView.onRestoreInstanceState(DestinationFragmentView.kt:187)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at android.view.View.dispatchRestoreInstanceState(View.java:20743)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3986)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at android.view.View.restoreHierarchyState(View.java:20721)
> 11-15 22:50:36.070 E/ACRA    ( 5678): 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2181)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3491)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.os.Looper.loop(Looper.java:223)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at java.lang.reflect.Method.invoke(Native Method)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> 11-15 22:50:36.071 E/ACRA    ( 5678): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bb5ef2f, Dispatchers.Main.immediate]
> 11-15 22:50:36.071 D/ACRA    ( 5678): Building report
> 11-15 22:50:36.072 D/ACRA    ( 5678): Starting collectors with priority FIRST
> 11-15 22:50:36.073 D/ACRA    ( 5678): Calling collector org.acra.collector.DropBoxCollector
> 11-15 22:50:36.073 D/ACRA    ( 5678): Collector org.acra.collector.DropBoxCollector completed
> 11-15 22:50:36.073 D/ACRA    ( 5678): Calling collector org.acra.collector.LogCatCollector
> 11-15 22:50:36.074 D/ACRA    ( 5678): Calling collector org.acra.collector.StacktraceCollector
> 11-15 22:50:36.076 D/ACRA    ( 5678): Collector org.acra.collector.StacktraceCollector completed
> 11-15 22:50:36.079 D/ACRA    ( 5678): Retrieving logcat output (buffer:default)...
> 
> ```  
> 
> ### App information
> 
> ***App version***: `0.17.9` (`170999`)  
> ***Package name***: `org.jellyfin.androidtv`  
> ***Build***: 
> ```json
> {"BOARD":"PH0M_EA_T32","BOOTLOADER":"01.01.241022","BRAND":"Philips","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"PH0M_EA_T32","DISPLAY":"RTM2.210929.098 release-keys","FINGERPRINT":"Philips\/PH0M_EA_T32_2G\/PH0M_EA_T32:11\/RTM2.210929.098\/200820:user\/release-keys","HARDWARE":"m7332","HOST":"TWTPSA388-refplus","ID":"RTM2.210929.098","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"TPV","MODEL":"Philips UHD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"PH0M_EA_T32_2G","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1729591224000,"TYPE":"user","UNKNOWN":"unknown","USER":"jenkins","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"200820","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2024-10-01"}}
> ```  
> ***Build config***: 
> ```json
> {"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170999,"VERSION_NAME":"0.17.9"}
> ```  
> 
> ### Device information
> 
> ***Android version***: `11`  
> ***Device brand***: `Philips`  
> ***Device product***: `PH0M_EA_T32_2G`  
> ***Device model***: `Philips UHD Android TV`  
> 
> ### Crash information
> 
> ***Start time***: `2024-11-15T22:48:00.178+01:00`  
> ***Crash time***: `2024-11-15T22:50:36.128+01:00`  
>  

 _Originally posted by @heggrik in [#4099](https://github.com/jellyfin/jellyfin-androidtv/issues/4099#issuecomment-2480007653)_

**Comment by nielsvanvelzen** [comment]
This issue is confirmed fixed in the 0.18 beta cycle already.

**Comment by heggrik** [comment]
> This issue is confirmed fixed in the 0.18 beta cycle already.

Just tried with v0.18.0-beta.3 and have the same issue still, i see the bugfix was included in v0.17.9 however. 
Not sure if this is the same as #4099 but it does look like it.
