### ISSUE TITLE
"Play All" or "Shuffle" for an artist or albums plays a list of random songs

### ISSUE THREAD

**Issue by vmpyr** [jellyfin/jellyfin-androidtv#4648]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-androidtv/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

1. Open an album/artist's page.
2. Click on "Play All" (for artist page) or "Shuffle" (for artist page as well as album page).
3. Random assortment of songs is played.

The random assortment for artist page "Play All" is seemingly always the same (maybe a set seed somewhere in the code). I have to always go to the first song and then click play from here instead. Because of this, I'm unable to play a single artist without creating a playlist.

### Application version

0.18.8

### Where did you install the app from?

Amazon Appstore

### Device information

Fire TV Stick (3rd Gen)

### Android version

Fire OS 7.6.9.0

### Jellyfin server version

10.10.3

**Comment by mal20k** [comment]
Also seeing this issue. In the page for an album, "Shuffle All" will create a shuffled queue consisting of music from the entire library. The first song is always the same one not from the selected album. From the album page, "Play All" works as expected and adds the full album to the queue with no extras.

From the artist page, both "Play" and "Shuffle All" will create a shuffled queue of music from the entire library. The first song is always the same like the "Shuffle All" from the album page, but is a different song.

Application version
0.18.9

Where did you install the app from?
Google Play Store

Device information
Nvidia Shield (2019)

Android version
9.0.1(33.1.0.283)

Jellyfin server version
10.10.7

**Comment by BloodyIron** [comment]
I am having this issue for both Jellyfin Android TV and Jellyfin on Android sending via Chromecast. It seems all shuffle buttons/instructions I can find for both app versions results in what is being described above:

1. It doesn't shuffle based on current context, it shuffles ALL audio files in ALL libraries
2. It plays the same song first in this shuffle list, except it's _never_ a song I select

I can't find a workaround for this and I don't know when this started as I don't (yet) use Jellyfin in these regards frequently enough to have said back-history.

I also want to add that my Jellyfin server is a Docker Image running inside Kubernetes behind a Layer 2 Load-Balancer (long-winded reasons for this).

**Comment by vmpyr** [comment]
the issue still exists on the latest version of the application.

**Comment by nielsvanvelzen** [comment]
Thanks for reporting. this issue should be fixed in the next 0.19 beta.

**Comment by mal20k** [comment]
This issue is still present on latest release. Only difference is that the first song is now shuffled instead of being the same one each time. Both artist and album "shuffle all" will shuffle the entire library and not the specific artist/album.

Application version
0.19.0

Where did you install the app from?
APK on github

Device information
Nvidia Shield (2019)

Android version
9.2.1(33.2.0.326)

Jellyfin server version
10.11.1

**Comment by mal20k** [comment]
Did some basic looks through the logs and found a difference in the request between this app and the Web UI. It's possible the album or artist ID may be getting sent incorrectly formatted by the app. For example, for the same album, the app is requesting:
```
http://server.example.com/Items?isMissing=false&limit=150&recursive=true&fields=CanDelete&fields=ChannelInfo&fields=Chapters&fields=ChildCount&fields=CumulativeRunTimeTicks&fields=DateCreated&fields=DisplayPreferencesId&fields=Genres&fields=ItemCounts&fields=MediaSourceCount&fields=MediaSources&fields=MediaStreams&fields=Overview&fields=Path&fields=PrimaryImageAspectRatio&fields=Taglines&fields=Trickplay&mediaTypes=Audio&sortBy=Random&albumIds=8b425867-284e-6d9d-16fa-ebab50391003&enableTotalRecordCount=true&enableImages=true
```

while the web UI is sending:
```
https://server.example.com/Users/db2fef3832ea4413beae15e57faa6c17/Items?ParentId=8b425867284e6d9d16faebab50391003&Filters=IsNotFolder&Recursive=true&SortBy=Random&MediaTypes=Audio,Video&Limit=300&Fields=Chapters,Trickplay&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false
```

Outside of specific options (or usage of parentId vs albumIds), the main difference I can see is the album ID is formatted differently, the app has dashes and the web ui is just plain. 
```
app: 8b425867-284e-6d9d-16fa-ebab50391003
webui: 8b425867284e6d9d16faebab50391003
```

My assumption is that this is being rejected by the server as that album ID does not exist and the server is then returning all audio tracks instead of only the ones with a parent or album ID matching.

Edit:
On a second check, not sure if that's related in any way. Direct retrieval of items using the dashed IDs appears to work as expected using "Play" and "Play from here".
