### ISSUE TITLE
Problem with forced video to 720 on Nvidia Shield TV Android TV

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-androidtv#469]
**Describe the bug**
It doesnt matter which movie/series i choose on my Nvidia Shield androidTV, the played file will be played on 720p. I see this because my TV jumps to the 720p resolution and the jellyfin GUI is scaled correctly but i see a really bad quality of the gui elements.
Testet a 1080p and 4k movie.

**To Reproduce**
Every video file.
I have now Jellyfin 10.5.5 installed and did an downgrade 10.5.4. but still same problem.
After downgrade to version 10.5.3 it is working again

**Expected behavior**
Played in correctly format

**Logs**
What log would be interesting?

**System (please complete the following information):**
 - Android TV
 - Device manufacturer: Nvidia
 - Device model: Shield TV]
 - Jellyfin server version: 10.5.4 and 10.5.5

**Comment by ryperx** [comment]
Anybody else has this behavior? Is this a AndroidTV Bug or a webserverbug? Because it happens only with latest version

**Comment by brabs27** [comment]
Hi, after installing Jellyfin yesterday, On my 2019 shield pro, my 1080i live tv streams are being displayed at 720p. Movie worked at 1080p but with no Atmos audio, which a different issue.

**Comment by j-stienstra** [comment]
Hi, I can reproduce this issue on my nVidia Shield TV with any media I play. Unlike ryperx, downgrading to 10.5.3 on the server side does not seem to solve the problem.

I've run an ADB logcat while starting a playback and captured the following trace:
05-23 19:35:02.496  4082  4082 I Jellyfin-AndroidTV: Internal player would direct stream
05-23 19:35:02.496  4082  4082 I Jellyfin-AndroidTV: Explicit deinterlacing will NOT be used
05-23 19:35:02.496  4082  4082 I Jellyfin-AndroidTV: User preferred player is: auto
05-23 19:35:02.496  4082  4082 I Jellyfin-AndroidTV: Will use internal player
05-23 19:35:02.665  4082  4082 I Jellyfin-AndroidTV: Network buffer set to 600
05-23 19:35:02.669  4082  4082 D Jellyfin-AndroidTV: Surface attached
05-23 19:35:02.670  4082  4082 I Jellyfin-AndroidTV: Playing back in native mode.
05-23 19:35:02.671  4082  4082 I Jellyfin-AndroidTV: *** Best refresh mode is: 1/29.97003
05-23 19:35:02.671  4082  4082 I Jellyfin-AndroidTV: *** Attempting to change refresh rate from 22/59.94006
05-23 19:35:02.676  4082  4082 D Jellyfin-AndroidTV: Only one audio track.
05-23 19:35:02.677  4082  4082 D Jellyfin-AndroidTV: No sub tracks found.
05-23 19:35:02.680  4082  4082 I Jellyfin-AndroidTV: Video path set to: https://foo/Videos/foo/stream.mov?api_key=foo&DeviceId=foo&MediaSourceId=foo&Tag=foo&Static=true
05-23 19:35:02.688  4082  4082 D Jellyfin-AndroidTV: Adding request to queue: https://foo/Sessions/Playing
05-23 19:35:02.689  4082  4082 I Jellyfin-AndroidTV: Playback of <VIDEO_NAME> started.
05-23 19:35:02.695  3352  3352 D SurfaceFlinger: Set active config mode=0, type=0 flinger=0x286fc62000
05-23 19:35:02.695  3339  3339 V hwcomposer: hwc_setActiveConfig: set config 21
05-23 19:35:02.695  3339  3339 D hwcomposer: nvfb_lookup_mode: external: request: 21, real: 185
05-23 19:35:02.696  3339  3339 V hwcomposer: display 0: vblank period = 33366666 ns
05-23 19:35:02.696  3339  3339 V hwcomposer: Display 0 device size is 1280 x 720
05-23 19:35:02.696  3339  3339 V hwcomposer: Display 0 device clip is (0.0, 0.0, 1280.0, 720.0)
05-23 19:35:02.698  3713  3779 I DisplayManagerService: Display device changed: DisplayDeviceInfo{"Ingebouwd scherm": uniqueId="local:0", 1280 x 720, modeId 1, defaultModeId 22, supportedModes [{id=1, width=1280, height=720, fps=29.97003}, {id=2, width=1280, height=720, fps=23.976025}, {id=3, width=1920, height=1080, fps=29.97003}, {id=4, width=1920, height=1080, fps=23.976025}, {id=5, width=1280, height=720, fps=59.94006}, {id=6, width=1920, height=1080, fps=59.94006}, {id=7, width=3840, height=2160, fps=29.97003}, {id=8, width=3840, height=2160, fps=23.976025}, {id=9, width=1280, height=720, fps=30.0}, {id=10, width=1280, height=720, fps=24.0}, {id=11, width=1920, height=1080, fps=30.0}, {id=12, width=1920, height=1080, fps=24.0}, {id=13, width=1280, height=720, fps=60.000004}, {id=14, width=1280, height=720, fps=50.0}, {id=15, width=1920, height=1080, fps=50.0}, {id=16, width=3840, height=2160, fps=30.0}, {id=17, width=3840, height=2160, fps=25.0}, {id=18, width=3840, height=2160, fps=24.0}, {id=19, width=3840, height=2160, fps=50.0}, {id=20, width=3840, height=2160, fps=60.000004}, {id=21, width=1920, height=1080, fps=60.000004}, {id=22, width=3840, height=2160, fps=59.94006}], colorMode 0, supportedColorModes [0, 5, 7, 9, 11], HdrCapabilities android.view.Display$HdrCapabilities@40f3c928, density 320, 213.0 x 213.0 dpi, appVsyncOff 1000000, presDeadline 33366666, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
05-23 19:35:02.699  3352  3352 D SurfaceFlinger: duplicate layer name: changing SurfaceView - org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity to SurfaceView - org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity#2
05-23 19:35:02.699  3713  3852 I InputReader: Reconfiguring input devices.  changes=0x00000004
05-23 19:35:02.699  3352  3352 D SurfaceFlinger: duplicate layer name: changing Background for -SurfaceView - org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity to Background for -SurfaceView - org.jellyfin.androidtv/org.jellyfin.androidtv.playback.PlaybackOverlayActivity#2
05-23 19:35:02.707  3339  3339 V hwcomposer: update_layer_clip: layer_clip changed, updating to 1280 x 720
05-23 19:35:02.707  3339  3339 V hwcomposer: Display 0 layer size is 1280 x 720
05-23 19:35:02.708  3339  3339 V hwcomposer: Display 0 device size is 1280 x 720
05-23 19:35:02.708  3339  3339 V hwcomposer: Display 0 device clip is (0.0, 0.0, 1280.0, 720.0)
05-23 19:35:02.781  3339  3339 E hwcomposer: modes_match: field h_active mismatch 1280 - 3840
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: Headset UEVENT: {SUBSYSTEM=extcon, SEQNUM=5418, ACTION=change, DEVTYPE=extcon4, STATE=HDMI=1
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: DP=0
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: AUDIO_AUX0=0
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: AUDIO_AUX1=0
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: AUDIO_AUX2=0
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: AUDIO_AUX3=0, DEVPATH=/devices/extcon/extcon:disp-state/extcon/extcon4, NAME=extcon:disp-state}
05-23 19:35:02.823  3713  3849 V WiredAccessoryManager: newName=extcon4 newState=0 headsetState=0 prev headsetState=256
05-23 19:35:02.823  3713  3849 I WiredAccessoryManager: MSG_NEW_DEVICE_STATE
05-23 19:35:02.826  3713  3713 V WiredAccessoryManager: headsetName:  disconnected address: = aux1_audio
05-23 19:35:02.901  3713  3849 V WiredAccessoryManager: Headset UEVENT: {SUBSYSTEM=extcon, SEQNUM=5422, ACTION=change, DEVTYPE=extcon4, STATE=HDMI=1
05-23 19:35:02.901  3713  3849 V WiredAccessoryManager: DP=0
05-23 19:35:02.901  3713  3849 V WiredAccessoryManager: AUDIO_AUX0=0
05-23 19:35:02.901  3713  3849 V WiredAccessoryManager: AUDIO_AUX1=1
05-23 19:35:02.901  3713  3849 V WiredAccessoryManager: AUDIO_AUX2=0
05-23 19:35:02.901  3713  3849 V WiredAccessoryManager: AUDIO_AUX3=0, DEVPATH=/devices/extcon/extcon:disp-state/extcon/extcon4, NAME=extcon:disp-state}
05-23 19:35:02.996  3339  3339 V hwcomposer: HDR: Clear cached SMPTE 2086 metadata
05-23 19:35:02.996  3339  3339 V hwcomposer: setting property vendor.display-size to 1280x720
05-23 19:35:02.996  3339  3339 V hwcomposer: setting property vendor.tegra.display-size to 1280x720
05-23 19:35:03.003  3713  3765 I android_os_HwBinder: HwBinder: Starting thread pool for default::vendor.nvidia.hardware.graphics.display@1.0::INvDisplay

It looks like the device screen size is not determined correctly. The first entry in the available screen sizes seems to be chosen, while other screen sizes are available.
This log capture is from a 4k piece of video, but I can reproduce the issue for 1080p video as well.

**Comment by j-stienstra** [comment]
Hi, some more information. This problem can be reproduced by selecting Auto, exoplayer or libvlc as the media player. Using an externall app (MX Player in my case), the problem is resolved.

**Comment by ryperx** [comment]
After downgrade to 10.5.3 it worked now fine. I last week again a upgrade to 10.5.5 to test it again and i dont know why but it worked for some time. 
Since Sunday the error is back on 10.5.5. 
Will try an downgrade again or maybe something can point me in the right direction to help

**Comment by ryperx** [comment]
I have stillt his problem, my shield is using the wrong resolution and video crashes/stops after nearly exactly 10minutes every time.
When i restart the media file and fast forward to the same timestamp i can watch again about 10 minutes...

**Comment by ryperx** [comment]
> 
> 
> Hi, some more information. This problem can be reproduced by selecting Auto, exoplayer or libvlc as the media player. Using an external app (MX Player in my case), the problem is resolved.

Thanks for this information, using vlcplayer fixes the problem.

Anybody has an idea what is happening on the shield? 720p forced and crash after 10 minutes.

**Comment by ryperx** [comment]
Dont know why but jellyfin isnt useable on my ShieldTV. Switched now to emby.
Is only me having this problems? Sadly i have no other AndroidTV Box for testing.
On my Smartphone Android App or Browser it works fine.

**Comment by brabs27** [comment]
> Dont know why but jellyfin isnt useable on my ShieldTV. Switched now to emby.
> Is only me having this problems? Sadly i have no other AndroidTV Box for testing.
> On my Smartphone Android App or Browser it works fine.

Yep I had same issue, I moved to emby which for me has other issues related to watching tv that is being recorded while watching. I wish something worked perfect.

**Comment by f-bader** [comment]
Same problem on a Nvidia Shield TV (2019).
Every video is, according to the TV and the AVR, played in 720p.

**Comment by ryperx** [comment]
I use now Kodi with the Jellyfin Plugin on my Shields.
Works fine but still would prefer to use the app :/

**Comment by KnightNZ** [comment]
Bumping this for the devs - any word?

**Comment by nielsvanvelzen** [comment]
Our plan is to rewrite all playback related code because it's a mess and unmaintainable currently. This will take a while though so we do patch the current code from time to time. I think this issue might be related to the max bitrate setting.
Please try it again on a 10.6 (or 10.7) server with the debug version of the app and let me know if the issue persists.

**Comment by jkrentz** [comment]
I'm running 10.7 server with this debug build on my 2019 shield:
https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=26674&view=artifacts&pathAsName=false&type=publishedArtifacts

No longer dropping content to 720p. Everything I've tried so far is direct playing at the correct resolution.

**Comment by RaphMad** [comment]
Still happens (with release versions) as of today, waiting for merge of the mentioned rewrite into release to actually close the ticket.

**Comment by ex0nuss** [comment]
Are there any news on this topic? I just set up Jellyfin as a replacement for Plex but 1080p and 4k movies are played back at a super low quality...

**Comment by nielsvanvelzen** [comment]
Try changing the bitrate setting. It might be set to "auto" right now, which for some users doesn't work properly and ends up using a very low value.
