### ISSUE TITLE
[0.19.0 beta 1] App crash with server 10.11 rc5

### ISSUE THREAD

**Issue by ClappTV** [jellyfin/jellyfin-androidtv#4906]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-androidtv/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

The app simply closes while navigating through it, sending the error log to the server.

`---
client: Jellyfin for Android TV
client_version: 0.19.0-beta.1
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---

### Logs

***Stack Trace***: 
```log
java.lang.IllegalArgumentException: Required value was null.
	at org.jellyfin.androidtv.util.apiclient.JellyfinImageKt.getSeriesPrimaryImage(JellyfinImage.kt:164)
	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:379)
	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:146)
	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7953)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6742)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:7013)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6853)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6849)
	at androidx.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:1151)
	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1682)
	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:116)
	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:409)
	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1994)
	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2347)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4459)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10523)
	at androidx.leanback.widget.GridLayoutManager.layoutChild(GridLayoutManager.java:1836)
	at androidx.leanback.widget.GridLayoutManager$2.addItem(GridLayoutManager.java:1762)
	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:129)
	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:409)
	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1994)
	at androidx.leanback.widget.GridLayoutManager.scrollDirectionPrimary(GridLayoutManager.java:2512)
	at androidx.leanback.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:2464)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2161)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5927)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
  
***Logcat***: 
```log
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1994)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2347)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4459)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.View.layout(View.java:22868)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.View.layout(View.java:22868)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.View.layout(View.java:22868)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10523)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager.layoutChild(GridLayoutManager.java:1836)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager$2.addItem(GridLayoutManager.java:1762)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:129)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:409)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1994)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager.scrollDirectionPrimary(GridLayoutManager.java:2512)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.leanback.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:2464)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2161)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5927)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.os.Handler.handleCallback(Handler.java:938)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.os.Looper.loop(Looper.java:223)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at java.lang.reflect.Method.invoke(Native Method)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-05 20:17:31.915 E/AndroidRuntime(19030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-05 20:17:31.916 E/ACRA    (19030): ACRA caught a IllegalArgumentException for org.jellyfin.androidtv
09-05 20:17:31.916 E/ACRA    (19030): java.lang.IllegalArgumentException: Required value was null.
09-05 20:17:31.916 E/ACRA    (19030): 	at org.jellyfin.androidtv.util.apiclient.JellyfinImageKt.getSeriesPrimaryImage(JellyfinImage.kt:164)
09-05 20:17:31.916 E/ACRA    (19030): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:379)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:146)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7953)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6742)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:7013)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6853)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6849)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:1151)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1682)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:116)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:409)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1994)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2347)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4459)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.View.layout(View.java:22868)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.View.layout(View.java:22868)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.View.layout(View.java:22868)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10523)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.layoutChild(GridLayoutManager.java:1836)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager$2.addItem(GridLayoutManager.java:1762)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:129)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.Grid.appendVisibleItems(Grid.java:409)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1994)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.scrollDirectionPrimary(GridLayoutManager.java:2512)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.leanback.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:2464)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2161)
09-05 20:17:31.916 E/ACRA    (19030): 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5927)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.os.Handler.handleCallback(Handler.java:938)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.os.Looper.loop(Looper.java:223)
09-05 20:17:31.916 E/ACRA    (19030): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-05 20:17:31.916 E/ACRA    (19030): 	at java.lang.reflect.Method.invoke(Native Method)
09-05 20:17:31.916 E/ACRA    (19030): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-05 20:17:31.918 E/ACRA    (19030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-05 20:17:31.918 D/ACRA    (19030): Building report
09-05 20:17:31.920 D/ACRA    (19030): Starting collectors with priority FIRST
09-05 20:17:31.920 D/ACRA    (19030): Calling collector org.acra.collector.DropBoxCollector
09-05 20:17:31.920 D/ACRA    (19030): Collector org.acra.collector.DropBoxCollector completed
09-05 20:17:31.920 D/ACRA    (19030): Calling collector org.acra.collector.LogCatCollector
09-05 20:17:31.920 D/ACRA    (19030): Calling collector org.acra.collector.StacktraceCollector
09-05 20:17:31.921 D/ACRA    (19030): Collector org.acra.collector.StacktraceCollector completed
09-05 20:17:31.925 D/ACRA    (19030): Retrieving logcat output (buffer:default)...

```
  

### App information

***App version***: `0.19.0-beta.1` (`190001`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-da5c2b1b","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_4040.2147","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_4040.2147:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-6368-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1745434137000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_4040.2147","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2025-03-05"}}
```
  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":190001,"VERSION_NAME":"0.19.0-beta.1"}
```
  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2025-09-05T20:09:43.867+02:00`  
***Crash time***: `2025-09-05T20:17:31.956+02:00`  

`

### Application version

0.19.0 beta 1

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia shield pro

### Android version

last version

### Jellyfin server version

10.11.0 RC5

**Comment by nielsvanvelzen** [comment]
Thanks for reporting. While I haven't been able to reproduce the issue it should be fixed with the next beta.

**Comment by ClappTV** [comment]
@nielsvanvelzen 

Tested in beta 2 and this issue still occurs: the app closes for no apparent reason while browsing the catalog.

`---
client: Jellyfin for Android TV
client_version: 0.19.0-beta.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---

### Logs

***Stack Trace***: 
```log
java.lang.IllegalArgumentException: parameter must be a descendant of this view
	at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:6272)
	at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:6201)
	at android.view.ViewRootImpl$ViewPostImeInputStage.performFocusNavigation(ViewRootImpl.java:6120)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6242)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
  
***Logcat***: 
```log
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.os.MessageQueue.next(MessageQueue.java:335)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.os.Looper.loop(Looper.java:183)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at java.lang.reflect.Method.invoke(Native Method)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-11 19:51:12.474 E/MessageQueue-JNI(23971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-11 19:51:12.474 D/AndroidRuntime(23971): Shutting down VM
--------- beginning of crash
09-11 19:51:12.480 E/AndroidRuntime(23971): FATAL EXCEPTION: main
09-11 19:51:12.480 E/AndroidRuntime(23971): Process: org.jellyfin.androidtv, PID: 23971
09-11 19:51:12.480 E/AndroidRuntime(23971): java.lang.IllegalArgumentException: parameter must be a descendant of this view
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:6272)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:6201)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$ViewPostImeInputStage.performFocusNavigation(ViewRootImpl.java:6120)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6242)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.os.MessageQueue.next(MessageQueue.java:335)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.os.Looper.loop(Looper.java:183)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at java.lang.reflect.Method.invoke(Native Method)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-11 19:51:12.480 E/AndroidRuntime(23971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-11 19:51:12.481 E/ACRA    (23971): ACRA caught a IllegalArgumentException for org.jellyfin.androidtv
09-11 19:51:12.481 E/ACRA    (23971): java.lang.IllegalArgumentException: parameter must be a descendant of this view
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:6272)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:6201)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$ViewPostImeInputStage.performFocusNavigation(ViewRootImpl.java:6120)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6242)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6054)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5704)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5761)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5560)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5533)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5586)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5552)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5737)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5895)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3217)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2759)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2750)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3194)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.os.MessageQueue.next(MessageQueue.java:335)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.os.Looper.loop(Looper.java:183)
09-11 19:51:12.481 E/ACRA    (23971): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
09-11 19:51:12.481 E/ACRA    (23971): 	at java.lang.reflect.Method.invoke(Native Method)
09-11 19:51:12.481 E/ACRA    (23971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-11 19:51:12.481 E/ACRA    (23971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-11 19:51:12.481 D/ACRA    (23971): Building report
09-11 19:51:12.484 D/ACRA    (23971): Starting collectors with priority FIRST
09-11 19:51:12.485 D/ACRA    (23971): Calling collector org.acra.collector.DropBoxCollector
09-11 19:51:12.485 D/ACRA    (23971): Collector org.acra.collector.DropBoxCollector completed
09-11 19:51:12.485 D/ACRA    (23971): Calling collector org.acra.collector.LogCatCollector
09-11 19:51:12.486 D/ACRA    (23971): Calling collector org.acra.collector.StacktraceCollector
09-11 19:51:12.487 D/ACRA    (23971): Collector org.acra.collector.StacktraceCollector completed
09-11 19:51:12.498 D/ACRA    (23971): Retrieving logcat output (buffer:default)...

```
  

### App information

***App version***: `0.19.0-beta.2` (`190002`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-da5c2b1b","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_4040.2147","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_4040.2147:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-6368-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1745434137000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_4040.2147","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2025-03-05"}}
```
  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":190002,"VERSION_NAME":"0.19.0-beta.2"}
```
  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2025-09-11T19:31:36.101+02:00`  
***Crash time***: `2025-09-11T19:51:12.535+02:00`  
`

**Comment by nielsvanvelzen** [comment]
Different crash, please open a new issue.
