### ISSUE TITLE
[V.0.19.0 beta 2] Forced remux for MP4/MKV containers (direct play broken)

### ISSUE THREAD

**Issue by Hukuma1** [jellyfin/jellyfin-androidtv#4931]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-androidtv/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

```
Remuxing
The media is in an incompatible file container (MKV, AVI, WMV, etc) but both the video stream and audio stream are compatible with the device. The media will be repackaged losslessly on the fly before being sent to the device.


Remux uses very little processing power with a completely lossless media quality.
```
Playing an MP4 file that would normally be a direct play is now triggering  remuxing. 1080p HEVC with AAC audio playing on an Nvidia Shield.

Logs below:

MP4:

```
{"Protocol":0,"Id":"b4bcc4bdb08fa60c6daf8a18e6f5dec2","Path":"/media/Media/Movies/Movie/Movie.mp4","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":2829157605,"Name":"Movie","IsRemote":false,"ETag":"a0e25bfa4924ad5b5c1233586867ab56","RunTimeTicks":101439350000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"English - SUBRIP - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/media/Media/Movies/Movie/Movie.en.srt","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"hevc","CodecTag":"hev1","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/24000","CodecTimeBase":null,"Title":null,"VideoRange":1,"VideoRangeType":1,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"1080p HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":2000324,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"ReferenceFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"16:9","Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":120,"IsAnamorphic":false},{"Codec":"aac","CodecTag":"mp4a","Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/48000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Default","LocalizedForced":null,"LocalizedExternal":"External","LocalizedHearingImpaired":null,"DisplayTitle":"English - AAC - 5.1 - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"5.1","BitRate":224000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":2231211,"FallbackMaxStreamingBitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null,"HasSegments":false}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts -f mov,mp4,m4a,3gp,3g2,mj2  -i file:"/media/Media/Movies/Movie/Movie.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/d5315f282e58895319cb174f8db3859e%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/d5315f282e58895319cb174f8db3859e.m3u8"


ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/media/Media/Movies/Movie/Movie.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2020-12-16T09:50:46.000000Z
    title           : Movie
    encoder         : Lavf58.20.100
    comment         : Movie
  Duration: 02:49:03.94, start: 0.000000, bitrate: 2231 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1920x1080 [SAR 1:1 DAR 16:9], 2000 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
      Metadata:
        creation_time   : 2020-12-16T09:50:46.000000Z
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
      Metadata:
        creation_time   : 2020-12-16T09:50:46.000000Z
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
[out#0/hls @ 0x55a3d5d7b200] Codec AVOption threads (set the number of threads) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Output #0, hls, to '/cache/transcodes/d5315f282e58895319cb174f8db3859e.m3u8':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 2000 kb/s, 23.98 fps, 23.98 tbr, 90k tbn (default)
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
Press [q] to stop, [?] for help
[hls @ 0x55a3d5d77f00] Opening '/cache/transcodes/d5315f282e58895319cb174f8db3859e0.ts' for writing
```

MKV:

```
{"Protocol":0,"Id":"c813aa7a81328b8139553ab2f8e3e619","Path":"/media2/Media/Cartoons/Cartoon.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv","Size":1307926823,"Name":"Cartoon","IsRemote":false,"ETag":"7a15848c76830c3a8b3db32da64d14ef","RunTimeTicks":29683520000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":1,"VideoRangeType":1,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"1080p HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":3524991,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":24,"RealFrameRate":24,"ReferenceFrameRate":24,"Profile":"Main 10","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":150,"IsAnamorphic":false},{"Codec":"eac3","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Default","LocalizedForced":null,"LocalizedExternal":"External","LocalizedHearingImpaired":null,"DisplayTitle":"English - Dolby Digital\u002B - Stereo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"stereo","BitRate":128000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":3652991,"FallbackMaxStreamingBitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null,"HasSegments":true}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:"/media2/Media/Cartoons/Cartoon.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/transcodes/c699eec7e9eacf8766bd396e246e031b%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/c699eec7e9eacf8766bd396e246e031b.m3u8"


ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, matroska,webm, from 'file:/media2/Media/Cartoons/Cartoon.mkv':
  Metadata:
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
    creation_time   : 2024-06-20T08:45:03.000000Z
  Duration: 00:49:28.35, start: 0.000000, bitrate: 3524 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 0.500000
      Metadata:
        title           : Part 01
    Chapter #0:1: start 0.500000, end 20.250000
      Metadata:
        title           : Intro
    Chapter #0:2: start 20.250000, end 2966.450000
      Metadata:
        title           : Part 02
    Chapter #0:3: start 2966.450000, end 2968.352000
      Metadata:
        title           : Credits
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 1920x1080, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn (default)
      Metadata:
        BPS             : 3395298
        DURATION        : 00:49:28.292000000
        NUMBER_OF_FRAMES: 71239
        NUMBER_OF_BYTES : 1259779800
        _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-06-20 08:45:03
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, stereo, fltp, 128 kb/s
      Metadata:
        BPS             : 128000
        DURATION        : 00:49:28.352000000
        NUMBER_OF_FRAMES: 92761
        NUMBER_OF_BYTES : 47493632
        _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-06-20 08:45:03
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[out#0/hls @ 0x562cc1828200] Codec AVOption threads (set the number of threads) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Output #0, hls, to '/cache/transcodes/c699eec7e9eacf8766bd396e246e031b.m3u8':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 24 fps, 24 tbr, 90k tbn (default)
  Stream #0:1: Audio: eac3, 48000 Hz, stereo, fltp, 128 kb/s
Press [q] to stop, [?] for help
[hls @ 0x562cc17ffd80] Opening '/cache/transcodes/c699eec7e9eacf8766bd396e246e031b0.ts' for writing
```

### Media info of the file

```shell

```

### FFmpeg logs

```shell

```

### Application version

0.19.0 b2

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield TV 2019

### Android version

Android 11

### Jellyfin server version

10.10.7

**Comment by nielsvanvelzen** [comment]
Please share a **media capability report**. This document contains a lot of data useful for troubleshooting playback related issues. To do some follow these steps:

1. Open the Jellyfin for Android TV app
2. Connect to a server **that you have admin access to**
3. Go to Preferences -> Playback -> Advanced playback preferences
4. On the bottom, press the "Report playback capabilities to server" button
5. Go to the logs in your Jellyfin dashboard (in your browser)
6. Open the newest log file, it should be named similar to `upload_Jellyfin Android TV[...].log`
7. Press the "Download" button and attach the file in a comment

**Comment by Hukuma1** [comment]
[Log.txt](https://github.com/user-attachments/files/22283842/Log.txt)

Here you go! Not sure if I'm interpreting the `Display Information` properly at the bottom, but it's weird to see that my LG C4 doesn't show to support Dolby Vision. But this is unrelated to this issue.

**Comment by BlackstormFirst** [comment]
Hello, I have the same issue with a fresh install of the 0.19.0 beta 2 on my Shield Pro 2019, now files are transcoded.
In addition, the admin web backend say : "The video range type is not supported."
Before that, the same video was only remuxed.

Have a nice day.

Edit: If I disable the ASS subtitles, the mkv video is now remuxed but with the same error cause as this issue.

**Comment by Leonashub** [comment]
> Hello, I have the same issue with a fresh install of the 0.19.0 beta 2 on my Shield Pro 2019, now files are transcoded. In addition, the admin web backend say : "The video range type is not supported." Before that, the same video was only remuxed.
> 
> Have a nice day.
> 
> Edit: If I disable the ASS subtitles, the mkv video is now remuxed but with the same error cause as this issue.

Have you tried the 11.11.0 rc or nightly version with the 0.19 beta version? Those have the same results as the current stable versions of both as far as I can remember from testing.

**Comment by BlackstormFirst** [comment]
> > Hello, I have the same issue with a fresh install of the 0.19.0 beta 2 on my Shield Pro 2019, now files are transcoded. In addition, the admin web backend say : "The video range type is not supported." Before that, the same video was only remuxed.
> > Have a nice day.
> > Edit: If I disable the ASS subtitles, the mkv video is now remuxed but with the same error cause as this issue.
> 
> Have you tried the 11.11.0 rc or nightly version with the 0.19 beta version? Those have the same results as the current stable versions of both as far as I can remember from testing.

Hello, in my case, you are partially right.
The video stream is remuxed because it's a mkv, as the prior version (my transcoding issue seems to be linked to the ASS part).

I'm still on the stable release on the server side like the opener of this issue.
Client version 0.19.x should work on both cases (10.10.7+ and 10.11.0+) as described.

Clients that continue to connect in 0.18.11 work as expected without transcode when they start a MKV(AVC/AAC/ASS), only a remux is expected, but with the new 0.19.x branch the video using an enabled ASS are now transcoded.

To get back to the subject, actually the MP4(AVC/AAC) container should be directly streamed without any transcode or remux, and should not be considered as an incompatible format.

Edit:
Without ASS
10.10.7 + 0.18.11 + MP4(AVC/AAC) = Direct
10.10.7 + 0.19.0b2 + MP4(AVC/AAC) = Remux

10.10.7 + 0.18.11 + MKV(AVC/AAC) = Remux
10.10.7 + 0.19.0b2 + MKV(AVC/AAC) = Remux

With ASS
10.10.7 + 0.18.11 + MP4(AVC/AAC)+ASS = Direct
10.10.7 + 0.19.0b2 + MP4(AVC/AAC)+ASS = Transcode

10.10.7 + 0.18.11 + MKV(AVC/AAC/ASS) = Remux
10.10.7 + 0.19.0b2 + MKV(AVC/AAC/ASS) = Transcode

**Comment by Hukuma1** [comment]
I personally would love to test 10.11 but I can't for some weird upgrade/migration reason: https://github.com/jellyfin/jellyfin/issues/14579

**Comment by Leonashub** [comment]
> I personally would love to test 10.11 but I can't for some weird upgrade/migration reason: [jellyfin/jellyfin#14579](https://github.com/jellyfin/jellyfin/issues/14579)

I have a separate docker install just to test it out with the media library set with read only permissions

**Comment by BlackstormFirst** [comment]
I just tried on another desktop with the server 10.11-rc5, I have the same issue with the 0.19-0b2.
The only one thing i quickly notice, it's the bug with the double same user/device witch is not present on the 10.11-rc5 against the 10.10.7 (on the admin page)

I currently have installed the studio to track where the change was made or missing during the revamp between the 0.18 and 0.19 branch and just finished to install the debug apk on my shield...

Edit:
Ok, i've made some new tests between 0.19.0b2 and the 10.11-rc5.

Without ASS
10.11-rc5 + 0.18.11 + MP4(AVC/AAC) = -
10.11-rc5 + 0.19.0b2 + MP4(AVC/AAC) = Direct

10.11-rc5 + 0.18.11 + MKV(AVC/AAC) = Remux
10.11-rc5 + 0.19.0b2 + MKV(AVC/AAC) = Direct

With ASS
10.11-rc5 + 0.18.11 + MP4(AVC/AAC)+ASS =  -
10.11-rc5 + 0.19.0b2 + MP4(AVC/AAC)+ASS = Transcode

10.11-rc5 + 0.18.11 + MKV(AVC/AAC/ASS) = Remux
10.11-rc5 + 0.19.0b2 + MKV(AVC/AAC/ASS) = Transcode

Edit2:
Ok, issues are vanished with the new server and the debug version without editing any piece of code.

Direct access issue is solved for MP4 and now work for MKV, but the fallback access (new client => old server) not work as the same at this point.

ASS is using the new libass (where the menu option is still not available except from the debug version), i think it should be enabled by default immediatly after the update, to avoid transcoding issues on client side...

In all cases it will be very fine to keep the fallback legacy method available, before the subtitle was forced to be encoded or explicitly asked from user/server config.

On otherside, the new ASS method seems to work... but the current fallback would be very appreciated especially if this part is still experimental ^^

**Comment by BlackstormFirst** [comment]
Just read the post about the libass... bad news... and.. huston.. we have a problem... libass or the rending of the ASS subs is the most important for me and clearly the "why" i chose Jellyfin and not another product... please do something and don't let the things in the current state for ASS.
If this release is pushed on the store without the menu option, you will have much more open issues about the transcoding...

**Comment by I-Vargas** [comment]
Background: Server is on `10.10.7` and CPU is an Intel N150

I've tried the beta, here's my media capability report: [beta.txt](https://github.com/user-attachments/files/22432751/beta.txt)
About this, it says `HDR10+: false` but my TV does have it...

I've tried to watch a 10-bit HEVC mp4 and it was remuxing, I uninstalled the beta and installed the stable release and it didn't remux.

Another side-effect, and the one that made me leave the beta, because of the remux, which I guess caused the A/V to be delayed, my subtitles (srt) were ahead of the A/V.

```
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 1.13 GiB
Duration                                 : 1 h 15 min
Overall bit rate                         : 2 134 kb/s
Frame rate                               : 23.976 FPS
```

**Comment by Hukuma1** [comment]
> Another side-effect, and the one that made me leave the beta, because of the remux, which I guess caused the A/V to be delayed, my subtitles (srt) were ahead of the A/V.

I saw something similar where the subtitles were off. I wasn't sure if it was a separate issue or related to this new remuxing behavior.

**Comment by nielsvanvelzen** [comment]
> [Log.txt](https://github.com/user-attachments/files/22283842/Log.txt)
> 
> Here you go! Not sure if I'm interpreting the `Display Information` properly at the bottom, but it's weird to see that my LG C4 doesn't show to support Dolby Vision. But this is unrelated to this issue.

Thanks, there doesn't seem to be anything weird here so I'd ask you to share client logs next. These should hopefully explain what's happening here.

This document explains how to capture logs: https://gist.github.com/nielsvanvelzen/96fd588194729d6845f2d5e414cffb8d

**Comment by arnokeesman** [comment]
Experiencing the same issue and had some time today, hope these logs can provide some insight

Running Jellyfin server 10.10.7 on an intel PC with Ubuntu Server and Docker using the LSIO image
The client app runs on a Nokia 8010
Direct playing these files does work on JF-AndroidTV v0.18.11
I first noticed the issue when trying to play a movie on beta1, did not have time to properly test back then, but the movie would not play before the server had time to remux the entire movie

The media files I used can be found in this [google drive folder](https://drive.google.com/drive/folders/1JxmeedtAtgmoafXv9rroiDOS2vEX7N4b) (not mine, I found it on reddit somwhere)

[media_capabilities_report.txt](https://github.com/user-attachments/files/22443457/media_capabilities_report.txt)

[atmos.log](https://github.com/user-attachments/files/22443470/atmos.log) (unfiltered adb log, started after navigating library, before starting playback, stopped a couple seconds after playback fininshed)
[Dolby Atmos E-AC-3 5.1.2.mp4.log](https://github.com/user-attachments/files/22443458/Dolby.Atmos.E-AC-3.5.1.2.mp4.log) (server/ffmpeg)

[ddp.log](https://github.com/user-attachments/files/22443475/ddp.log) (identically captured adb log)
[Dolby Digital Plus E-AC-3 5.1.mp4.log](https://github.com/user-attachments/files/22443460/Dolby.Digital.Plus.E-AC-3.5.1.mp4.log) (server/ffmpeg)

**Comment by Hukuma1** [comment]
> > [Log.txt](https://github.com/user-attachments/files/22283842/Log.txt)
> > Here you go! Not sure if I'm interpreting the `Display Information` properly at the bottom, but it's weird to see that my LG C4 doesn't show to support Dolby Vision. But this is unrelated to this issue.
> 
> Thanks, there doesn't seem to be anything weird here so I'd ask you to share client logs next. These should hopefully explain what's happening here.
> 
> This document explains how to capture logs: https://gist.github.com/nielsvanvelzen/96fd588194729d6845f2d5e414cffb8d

Hopefully I did it correctly:

Edited with Verbose output:

```
C:\adblink>adb logcat *:V | findstr org.jellyfin.androidtv
09-22 19:24:28.544  4746  7946 E AndroidRuntime: Process: org.jellyfin.androidtv, PID: 4746
09-22 23:00:16.838 18053 18053 E AndroidRuntime: Process: org.jellyfin.androidtv, PID: 18053
09-22 23:00:16.838 18053 18053 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2b24f44 u0 org.jellyfin.androidtv/org.jellyfin.playback.media3.session.AndroidMediaService}
09-23 22:15:12.148  3531  4816 I ActivityManager: Process org.jellyfin.androidtv.debug (pid 12849) has died: cch+45 CEM
09-24 03:28:21.939  3531  3605 I AppsFilter: interaction: PackageSetting{8a2d18f org.jellyfin.androidtv.debug/10132} -> PackageSetting{cc6fc1c com.netflix.ninja/10015} BLOCKED
09-24 03:28:30.079  3531  3605 I AppsFilter: interaction: PackageSetting{8a2d18f org.jellyfin.androidtv.debug/10132} -> PackageSetting{cc6fc1c com.netflix.ninja/10015} BLOCKED
09-24 08:24:41.586  3531  3556 I ActivityManager: Start proc 11166:org.jellyfin.androidtv.debug/u0a132 for content provider {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.integration.provider.ImageProvider}
09-24 08:24:43.363  3531  3545 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=org.jellyfin.androidtv cmp=org.jellyfin.androidtv/.ui.startup.StartupActivity} from uid 10128
09-24 08:24:44.583  3531  4711 I ActivityTaskManager: START u0 {flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity} from uid 10055
09-24 08:24:44.612  3531  4711 W ActivityTaskManager: Duplicate finish request for r=ActivityRecord{650393 u0 org.jellyfin.androidtv/.ui.startup.StartupActivity t3526 f}}
09-24 08:47:33.237  3531  7511 I ActivityManager: Process org.jellyfin.androidtv.debug (pid 11166) has died: cch+55 CEM
09-24 11:29:01.119  3531  3605 I AppsFilter: interaction: PackageSetting{8a2d18f org.jellyfin.androidtv.debug/10132} -> PackageSetting{cc6fc1c com.netflix.ninja/10015} BLOCKED
09-24 11:29:09.031  3531  3605 I AppsFilter: interaction: PackageSetting{8a2d18f org.jellyfin.androidtv.debug/10132} -> PackageSetting{cc6fc1c com.netflix.ninja/10015} BLOCKED
09-24 14:37:04.945 25301 25301 D ACRA    : onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:37:05.561  3531  3556 I ActivityManager: Start proc 24969:org.jellyfin.androidtv.debug/u0a132 for content provider {org.jellyfin.androidtv.debug/org.jellyfin.androidtv.integration.provider.ImageProvider}
09-24 14:37:05.580 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 37 lines
09-24 14:37:05.764 25301 25301 D ACRA    : onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:37:05.806 25301 25301 D ACRA    : onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:37:06.579 24969 25030 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 13 lines
09-24 14:37:06.600 24969 25035 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-1 expire 3 lines
09-24 14:37:06.652 24969 25038 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 3 lines
09-24 14:37:06.839 24969 25031 I chatty  : uid=10132(org.jellyfin.androidtv.debug) DefaultDispatch expire 2 lines
09-24 14:37:06.968 24969 25047 I chatty  : uid=10132(org.jellyfin.androidtv.debug) GrallocUploadTh expire 98 lines
09-24 14:37:07.099 24969 25048 I chatty  : uid=10132(org.jellyfin.androidtv.debug) RenderThread expire 4 lines
09-24 14:37:07.194  3531  7534 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=org.jellyfin.androidtv.debug cmp=org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.startup.StartupActivity} from uid 10128
09-24 14:37:07.413 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 12 lines
09-24 14:37:07.533  3531  4816 I NvUtils : onActivityResumed AM packageName = org.jellyfin.androidtv.debug
09-24 14:37:07.567 24969 25041 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-3 expire 3 lines
09-24 14:37:07.585 24969 25035 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-1 expire 1 line
09-24 14:37:07.600 24969 25032 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.600 24969 25054 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.623  3737  3737 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.jellyfin.androidtv
09-24 14:37:07.623  3737  3737 D AvrcpMediaPlayerList: Already have a controller for the player: org.jellyfin.androidtv, updating instead
09-24 14:37:07.640  4897  4897 D DeviceControlManagerService: active session:org.jellyfin.androidtv
09-24 14:37:07.649 24969 25040 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-2 expire 1 line
09-24 14:37:07.652 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.656 24969 25040 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-2 expire 1 line
09-24 14:37:07.675 24969 25041 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-3 expire 2 lines
09-24 14:37:07.805 24969 25048 I chatty  : uid=10132(org.jellyfin.androidtv.debug) RenderThread expire 5 lines
09-24 14:37:07.866  3531  3554 D ArtManagerInternalImpl: /data/misc/iorapd/org.jellyfin.androidtv.debug/190003/org.jellyfin.androidtv.ui.startup.StartupActivity/compiled_traces/compiled_trace.pb doesn't exist
09-24 14:37:07.872 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 6 lines
09-24 14:37:07.887  3531  3554 I ActivityTaskManager: Displayed org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.startup.StartupActivity: +658ms
09-24 14:37:07.941 24969 25053 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.943 24969 25055 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.945 24969 25061 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.947 24969 25053 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.948 24969 25055 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.948 24969 25053 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.949 24969 25062 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 2 lines
09-24 14:37:07.952 24969 25030 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.953 24969 25053 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.953 24969 25031 I chatty  : uid=10132(org.jellyfin.androidtv.debug) DefaultDispatch expire 1 line
09-24 14:37:07.953 24969 25030 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.957 24969 25061 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.958 24969 25032 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.968 24969 25062 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:07.972  3737  3737 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.jellyfin.androidtv
09-24 14:37:07.972  3737  3737 D AvrcpMediaPlayerList: Already have a controller for the player: org.jellyfin.androidtv, updating instead
09-24 14:37:07.974  4897  4897 D DeviceControlManagerService: active session:org.jellyfin.androidtv
09-24 14:37:07.982 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 2 lines
09-24 14:37:07.982  3737  3737 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.jellyfin.androidtv.debug
09-24 14:37:07.985  3531  4816 I ActivityTaskManager: START u0 {flg=0x10004000 cmp=org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity} from uid 10132
09-24 14:37:07.988 24969 25045 I chatty  : uid=10132(org.jellyfin.androidtv.debug) OkHttp Dispatch expire 2 lines
09-24 14:37:07.991 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 2 lines
09-24 14:37:08.004 24969 25032 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.008  3737  3737 I AvrcpMediaPlayerList: Adding wrapped media player: org.jellyfin.androidtv.debug at key: 2
09-24 14:37:08.015 24969 25055 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.020 24969 25054 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 2 lines
09-24 14:37:08.026 24969 25045 I chatty  : uid=10132(org.jellyfin.androidtv.debug) OkHttp Dispatch expire 1 line
09-24 14:37:08.041 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 3 lines
09-24 14:37:08.054 24969 25041 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-3 expire 1 line
09-24 14:37:08.084 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 6 lines
09-24 14:37:08.157  3531  7534 I NvUtils : onActivityResumed AM packageName = org.jellyfin.androidtv.debug
09-24 14:37:08.279 24969 25054 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 2 lines
09-24 14:37:08.291 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 4 lines
09-24 14:37:08.339 24969 25032 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.339 24969 25054 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.341 24969 25065 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.504 24969 25048 I chatty  : uid=10132(org.jellyfin.androidtv.debug) RenderThread expire 4 lines
09-24 14:37:08.583  3531  3554 I ActivityTaskManager: Displayed org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity: +597ms
09-24 14:37:08.644  3737  3737 D AvrcpMediaPlayerList: Name of package changed: org.jellyfin.androidtv.debug
09-24 14:37:08.650 24969 25032 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.651 24969 25030 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.653 24969 25066 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.657 24969 25031 I chatty  : uid=10132(org.jellyfin.androidtv.debug) DefaultDispatch expire 1 line
09-24 14:37:08.662 24969 25067 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.665 24969 25055 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.667 24969 25054 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:08.724 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 12 lines
09-24 14:37:09.638 24969 25048 I chatty  : uid=10132(org.jellyfin.androidtv.debug) RenderThread expire 3 lines
09-24 14:37:09.755 24969 25076 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:09.771 24969 24983 I chatty  : uid=10132(org.jellyfin.androidtv.debug) HeapTaskDaemon expire 2 lines
09-24 14:37:11.261 24969 25040 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-2 expire 2 lines
09-24 14:37:11.266 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 2 lines
09-24 14:37:11.279 24969 25040 I chatty  : uid=10132(org.jellyfin.androidtv.debug) WM.task-2 expire 1 line
09-24 14:37:12.197 24969 25142 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:15.123 24969 24983 I chatty  : uid=10132(org.jellyfin.androidtv.debug) HeapTaskDaemon expire 1 line
09-24 14:37:17.200 24969 25047 I chatty  : uid=10132(org.jellyfin.androidtv.debug) GrallocUploadTh expire 4 lines
09-24 14:37:29.272 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 4 lines
09-24 14:37:29.360 24969 25031 I chatty  : uid=10132(org.jellyfin.androidtv.debug) DefaultDispatch expire 1 line
09-24 14:37:29.444 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 4 lines
09-24 14:37:29.612 24969 25031 I chatty  : uid=10132(org.jellyfin.androidtv.debug) DefaultDispatch expire 1 line
09-24 14:37:30.198 24969 25048 I chatty  : uid=10132(org.jellyfin.androidtv.debug) RenderThread expire 1 line
09-24 14:37:30.292 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:30.379 24969 25047 I chatty  : uid=10132(org.jellyfin.androidtv.debug) GrallocUploadTh expire 4 lines
09-24 14:37:30.514 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:30.557 24969 24983 I chatty  : uid=10132(org.jellyfin.androidtv.debug) HeapTaskDaemon expire 1 line
09-24 14:37:36.780 24969 25067 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 1 line
09-24 14:37:36.800 24969 24969 I chatty  : uid=10132(org.jellyfin.androidtv.debug) expire 5 lines
09-24 14:37:37.164  3531  7991 I MediaFocusControl: requestAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@c178b24org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@443668d callingPack=org.jellyfin.androidtv.debug req=1 flags=0x0 sdk=36
09-24 14:37:38.145 24969 25285 I chatty  : uid=10132(org.jellyfin.androidtv.debug) identical 2 lines
09-24 14:37:38.384  3531  3531 D MediaSessionService: Media button session is changed to org.jellyfin.androidtv.debug/androidx.media3.session.id.1 (userId=0)
09-24 14:37:38.388  4897  4897 D DeviceControlManagerService: active session:org.jellyfin.androidtv
09-24 14:37:38.388  3737  3737 I AvrcpMediaPlayerList: onMediaKeyEventSessionChanged: token=org.jellyfin.androidtv.debug
09-24 14:37:38.420  3737  3737 D AvrcpMediaPlayerList: setActivePlayer(): setting player to org.jellyfin.androidtv.debug
09-24 14:37:38.423  3737  3737 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.jellyfin.androidtv
09-24 14:37:38.423  3737  3737 D AvrcpMediaPlayerList: Already have a controller for the player: org.jellyfin.androidtv, updating instead
09-24 14:37:38.423  3737  3737 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.jellyfin.androidtv.debug
09-24 14:37:38.423  3737  3737 D AvrcpMediaPlayerList: Already have a controller for the player: org.jellyfin.androidtv.debug, updating instead
09-24 14:38:56.651  3531  7511 I MediaFocusControl: abandonAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@c178b24org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@443668d
09-24 14:38:56.655  3531  7511 I MediaFocusControl: abandonAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@c178b24org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@443668d
09-24 14:39:00.561 24969 24969 D NavigationRepositoryImpl: Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment (Kotlin reflection is not available), arguments=Bundle[{Position=0}]) (via navigate function)
09-24 14:39:00.743  3531  4222 I MediaFocusControl: requestAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@c178b24org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@9b50e35 callingPack=org.jellyfin.androidtv.debug req=1 flags=0x0 sdk=36
09-24 14:39:01.288 24969 25761 I chatty  : uid=10132(org.jellyfin.androidtv.debug) identical 2 lines
09-24 14:44:12.772  3737  3737 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.jellyfin.androidtv.debug
09-24 14:44:12.772  3737  3737 D AvrcpMediaPlayerList: Already have a controller for the player: org.jellyfin.androidtv.debug, updating instead
09-24 14:44:12.773  3531  7510 I ActivityManager: Process org.jellyfin.androidtv (pid 25301) has died: cch CRE
09-24 14:44:12.776  4897  4897 D DeviceControlManagerService: active session:org.jellyfin.androidtv.debug
09-24 14:49:55.100  3531  9316 I MediaFocusControl: abandonAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@c178b24org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@9b50e35
09-24 14:49:55.103  3531  9316 I MediaFocusControl: abandonAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@c178b24org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@9b50e35
09-24 14:49:58.308 24969 24969 D ACRA    : onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:49:59.020 24969 24969 D ACRA    : onActivityStopped class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:49:59.128 24969 24969 D ACRA    : onActivityDestroyed class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:50:00.458 24969 24969 D WM-WorkerWrapper: Starting work for org.jellyfin.androidtv.integration.LeanbackChannelWorker
09-24 14:50:08.489  3531  3531 W JobServiceContext: No response from client for onStartJob 4d94484 #u0a132/22 org.jellyfin.androidtv.debug/androidx.work.impl.background.systemjob.SystemJobService
09-24 14:50:08.798 24969 25035 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=87122c63-f4a4-4590-bb35-869bb7f705b9, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
09-24 14:50:20.018  3531  8103 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=org.jellyfin.androidtv.debug cmp=org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.startup.StartupActivity} from uid 10128
09-24 14:50:20.069 24969 24969 D ACRA    : onActivityCreated class org.jellyfin.androidtv.ui.startup.StartupActivity
09-24 14:50:20.104 24969 24969 D ACRA    : onActivityStarted class org.jellyfin.androidtv.ui.startup.StartupActivity
09-24 14:50:20.113 24969 24969 D ACRA    : onActivityResumed class org.jellyfin.androidtv.ui.startup.StartupActivity
09-24 14:50:20.135  3531  7510 I NvUtils : onActivityResumed AM packageName = org.jellyfin.androidtv.debug
09-24 14:50:20.310  3531  3554 D ArtManagerInternalImpl: /data/misc/iorapd/org.jellyfin.androidtv.debug/190003/org.jellyfin.androidtv.ui.startup.StartupActivity/compiled_traces/compiled_trace.pb doesn't exist
09-24 14:50:20.311  3531  3554 I ActivityTaskManager: Displayed org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.startup.StartupActivity: +248ms
09-24 14:50:20.343 24969 24969 D NavigationRepositoryImpl: Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via reset, clearHistory=true)
09-24 14:50:20.344 24969 24969 D StartupActivity: Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity }
09-24 14:50:20.345  3531  9316 I ActivityTaskManager: START u0 {flg=0x10004000 cmp=org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity} from uid 10132
09-24 14:50:20.357 24969 24969 D ACRA    : onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
09-24 14:50:20.377 24969 24969 D ACRA    : onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:50:20.398 24969 24969 D ACRA    : onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:50:20.401 24969 24969 D ACRA    : onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
09-24 14:50:20.422  3531  9316 I NvUtils : onActivityResumed AM packageName = org.jellyfin.androidtv.debug
09-24 14:50:20.427 24969 24969 D WM-WorkerWrapper: Starting work for org.jellyfin.androidtv.integration.LeanbackChannelWorker
09-24 14:50:20.626  3531  3554 I ActivityTaskManager: Displayed org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity: +280ms
09-24 14:50:21.332 24969 24969 D ACRA    : onActivityStopped class org.jellyfin.androidtv.ui.startup.StartupActivity
09-24 14:50:21.337 24969 24969 D ACRA    : onActivityDestroyed class org.jellyfin.androidtv.ui.startup.StartupActivity
09-24 14:50:22.489 24969 25041 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=68f23d7d-00f1-436e-bb81-d3eae340b7fe, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
09-24 14:50:35.982 24969 24969 D NavigationRepositoryImpl: Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment (Kotlin reflection is not available), arguments=Bundle[{ItemId=db417fc4-2ea0-2215-f53e-110f25f74259}]) (via navigate function)
09-24 14:50:43.789 24969 24969 D NavigationRepositoryImpl: Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment (Kotlin reflection is not available), arguments=Bundle[{Position=0}]) (via navigate function)
09-24 14:50:44.022  3531  3777 I MediaFocusControl: requestAudioFocus() from uid/pid 10132/24969 clientId=android.media.AudioManager@31dc7eorg.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@ddd75df callingPack=org.jellyfin.androidtv.debug req=1 flags=0x0 sdk=36
09-24 14:50:44.745 24969 29349 I chatty  : uid=10132(org.jellyfin.androidtv.debug) ExoPlayer:Playb identical 1 line
09-24 14:50:44.800 24969 29349 I chatty  : uid=10132(org.jellyfin.androidtv.debug) ExoPlayer:Playb identical 1 line
```

[The instructions for Windows logging](https://gist.github.com/nielsvanvelzen/96fd588194729d6845f2d5e414cffb8d?permalink_comment_id=5372097#gistcomment-5372097) gave me an error: `C:\adblink>adb logcat | ForEach-Object { $_ } | Select-String -Pattern "org.jellyfin.androidtv"
'ForEach-Object' is not recognized as an internal or external command,
operable program or batch file.`

These logs are coming from beta 3 now. So still the same issue. Forcing a remux.

**Comment by Hukuma1** [comment]
After upgrading to Jellyfin server `10.11.0 RC6` it works without remuxing again. I don't really have time to debug why it doesn't work on the older stable version, but since it works on the upcoming Jellyfin version perhaps you should just delay the release of `V.0.19.0` to release at the same time?

**Comment by Leonashub** [comment]
> After upgrading to Jellyfin server `10.11.0 RC6` it works without remuxing again. I don't really have time to debug why it doesn't work on the older stable version, but since it works on the upcoming Jellyfin version perhaps you should just delay the release of `V.0.19.0` to release at the same time?

Im almost sure that they already announced the stable versions release (closely) together

**Comment by Pentaphon** [comment]
@Hukuma1 what happens if you disable transcoding altogether for your account? I find that directplay, even on the latest 0.19 beta 4, is totally broken to the point that disabling transcoding altogether makes it impossible to play any files with the stable 10.10.7 server.

**Comment by Leonashub** [comment]
> [@Hukuma1](https://github.com/Hukuma1) what happens if you disable transcoding altogether for your account? I find that directplay, even on the latest 0.19 beta 4, is totally broken to the point that disabling transcoding altogether makes it impossible to play any files with the stable 10.10.7 server.

There are backend changes to the server side. The beta won't work well with the stable server version

**Comment by Pentaphon** [comment]
> There are backend changes to the server side. The beta won't work well with the stable server version

In that case, these beta releases should come with a notice that the server should be updated to the latest testing version as well. It doesn't really make sense for a client to have broken functionality with the latest stable server. Most people will never update to a beta version of the server but they will be likely to test out a beta version of a client.

**Comment by nielsvanvelzen** [comment]
The 0.19 release of the app supports both Jellyfin 10.10 and Jellyfin 10.11. The only thing is that some changes may depend on Jellyfin 10.11. For example, the improvements to DoVi playback require 10.11.

**Comment by nielsvanvelzen** [comment]
Thanks for the report. This issue should be fixed with beta 5, let me know if it doesn't!

**Comment by Hukuma1** [comment]
Unfortunately I already took the plunge on Jellyfin 10.11 RC. If anyone else that's currently on stable can please test and see if it's fixed in b5, I'll happily close this one out. Thank you!

**Comment by Leonashub** [comment]
> Unfortunately I already took the plunge on Jellyfin 10.11 RC. If anyone else that's currently on stable can please test and see if it's fixed in b5, I'll happily close this one out. Thank you!

Direct play works again on the stable server version with 0.19 beta 5. (On firestick 4k max 2nd(other known bugs still present on this particular device but thats expected since the fix for that isn't there yet)).
