### ISSUE TITLE
Set default subtitle and audio track

### ISSUE THREAD

**Issue by ixanx** [jellyfin/jellyfin-androidtv#562]
On Android TV, whenever I click on an episode, I have to manually select the subtitle and audio track, or sometimes it defaults to the english one, when I always set it to japanese, which is an inconvenient.
Thanks a lot, this bugs me a lot :(

**Comment by Yumega** [comment]
I agree with you, I need Chinese in default

**Comment by xinstein** [comment]
+1

**Comment by HavermansStef** [comment]
I'm also experiencing. I need to select subtitles every time. Sometimes they also automatically get loaded, but most of the time these are the subs of the previous episode.

**Comment by zilexa** [comment]
I believe the description of this issue is not entirely complete.
To reproduce:
1) select default languages for audio and subtitles in Jellyfin Server, for example English.
2) on Jellyfin-AndroidTV, play a video with multiple audiotracks, for example the first track is French, second is English.
3) notice the French track is being played.

Quite annoying.

**Comment by Norin-Radd** [comment]
1. setup portuguese as the default subtitle and to always play
2. on android tv app the movie plays without loading the default subtitle a person has to manually choose the sub
on kodi works as intended

**Comment by julienfroidefond** [comment]
I see this code in the media player : 
`mDefaultSubIndex = mPlaybackMethod != PlayMethod.Transcode && response.getMediaSource().getDefaultSubtitleStreamIndex() != null ? response.getMediaSource().getDefaultSubtitleStreamIndex() : mDefaultSubIndex;`
I don't understand what sets the default subtitle on media source. But I think that subtitles preferences are dependent of the device (web != android tv) ; I don't see preferences in the server dashboard. Should you introduce another android tv preference for default audio and subtitle ?

**Comment by ItsMeAPizza** [comment]
+1
Using a firestick and get the same issue of not being able to keep a default language for audio and subtitles and

Additionally, the if the media is paused and you try to switch audio track the track doesn't switch to the newly selected audio

**Comment by avion540** [comment]
Just commenting because this is still an issue

**Comment by seelenamt** [comment]
Commenting on this too. If this is being worked on, please allow for setting per-series default audio and subtitle tracks, instead of a just a global setting!

**Comment by zilexa** [comment]
I was also looking for the code that sets the default audio track and subtitles language. Couldn't find it.

**Comment by DrGonzo94** [comment]
I have this issue as well. I would very much like a subtitles always on feature.

**Comment by cyphar** [comment]
It seems strange that you can configure this setting in the web version but not for Android TV (I appreciate they're different codebases, but as a new Jellyfin user I found it quite confusing trying to figure out which settings apply to the user across all devices and which are device-specific).

**Comment by didaktiik** [comment]
I have this "issue" as well even it should be seen as "a feature" at the moment, I believe :-) (Until next update, that is)
The fact is, Jellyfin in browser allows to choose default audio track but AndroidTV version does not.

4 things missing in AndroidTV version:

- ability to choose between movies versions
- set default audio track preference
- subtitles size and color
- photos/pictures .. play a slideshow (if it's there, I don't know how to..)

All 4 four are present in web Jellyfin :+1:

**Comment by zilexa** [comment]
It is strange to me that we have 2 major versions now, and still the bare basics are not taken care of. Not being able to set default languages and set a sane subtitle size and colour defeats reason for most to even enjoy those new versions. 
I'm still on Kodi only for this reason. Doesn't make sense to me this still has no priority :(

**Comment by vulporuza** [comment]
Same here using v0.13.0-beta.3, please use account default setting :)

**Comment by cirdanmiriel** [comment]
Same here, this would be a great feature

**Comment by zilexa** [comment]
Will this be fixed before the final v13.0 release?

**Comment by mueslimak3r** [comment]
this issue should be fixed in 0.13. The player should now use the "default" audio track chosen by the server. The track is either:
* the track chosen when the video was last played
* the track that's chosen due to a user's language preference or because it is marked as forced

**Comment by nielsvanvelzen** [comment]
This should be fixed now, let us know if the issue still persists in the latest version (0.14).

**Comment by NightHammer1000** [comment]
Well. I still have this Issue one some of my Animes.
The Tracks are tagged correctly as eng and jap in the Media File. 
My Profile on the Server is set to prefer English. 
Yet some Animes, especially those who have the Japanese Track as Track 1 will default to Japanese.

**Comment by Avrution** [comment]
> Well. I still have this Issue one some of my Animes. The Tracks are tagged correctly as eng and jap in the Media File. My Profile on the Server is set to prefer English. Yet some Animes, especially those who have the Japanese Track as Track 1 will default to Japanese.

Ditto.  I'm using the roku client, so it could also be related to that.

**Comment by Will-Schr** [comment]
I'm also still having issues with the android tv client not keeping subtitle/audio track choices between episodes of a series

**Comment by Katharta** [comment]
Hey, I'm on Android TV app version 0.15.12 and audio track preference is not being remembered from episode to episode for at least one series in my library. Potentially related, when I initially select the audio track I want, it is not applied. I have to select it, select the original, then select the other again before it actually switches over. Is there any info I can provide to help?

**Comment by Martan404** [comment]
I have video files that comes with multiple subtitle files included inside it and with a default already set for which language to use. The language I want get detected and labeled correctly by Jellyfin when open the menu to change it but Jellyfin won't respect my settings to always use the language of my choice.

**Comment by AnnoyedLeek** [comment]
I am also having this issue on my Roku stick. I set the default language for each individual episode of a show. I cannot blanket apply the setting; it is not respected. This also occurs in the web app.

**Comment by thor9898** [comment]
It keeps happening to me on the firetv app

**Comment by fogolin** [comment]
can we reopen this issue?

**Comment by mirhen2023** [comment]
Any idea when this issue is going to be solved?

**Comment by maxi1134** [comment]
The problem is still present

**Comment by mkgeeky** [comment]
Please fix this.

**Comment by Nenormalniy** [comment]
This issue should be reopened.

**Comment by zilexa** [comment]
I've made a point of lack of basic subtitle/audio features, such as selecting default track, always have subtitles etc. 
Truly basic stuff. So many other huge things have been done, rewrite of backend and what not.. 
But Jellyfin for AndroidTV is not usable in my opinion due to these issues. Which is a pity, considering all the dev time that has gone into Jellyfin. 

I only use Jellyfin once every few months to see if things have improved. Been using it like that for over a year. Always run back to Kodi (with Jellyfin addon in addon-mode). I would really prefer to just use Jellyfin. 

I don't expect this to change. Focus is simply not on "usability" or whatever you want to call being able to hear and read what you configured.
